// ============================================================
// Yene QR — Ethiopian Restaurant Data Module
// 10 unique restaurants showcasing platform capabilities
// ============================================================

module.exports = [
  {
    id: 'rest-habesha',
    slug: 'habesha-restaurant',
    name: 'Habesha Maebel',
    nameAm: 'ሐበሻ ማዕበል',
    description: 'Addis Ababa\'s premier traditional Ethiopian dining experience with live cultural music and panoramic city views from our rooftop terrace',
    descriptionAm: 'በአዲስ አበባ ዋና የባህላዊ ኢትዮጵያዊ ምግብ ቤት ስለተለያየ ባህላዊ ሙዚቃ እና ከጣሪያ ወጥቶ የሚታይ የከተማ እይታ',
    cuisineType: 'Ethiopian Traditional',
    phone: '+251911234567',
    email: 'info@habeshamaebel.et',
    address: 'Bole Road, Near Edna Mall',
    city: 'Addis Ababa',
    taxRate: 0.15,
    serviceCharge: 0.10,
    workingHours: '{"mon":{"open":"08:00","close":"22:00"},"tue":{"open":"08:00","close":"22:00"},"wed":{"open":"08:00","close":"22:00"},"thu":{"open":"08:00","close":"22:00"},"fri":{"open":"08:00","close":"23:00"},"sat":{"open":"09:00","close":"23:00"},"sun":{"open":"09:00","close":"21:00"}}',
    plan: 'plan-premium',
    branches: [
      {
        id: 'branch-habesha-bole',
        name: 'Bole Flagship',
        nameAm: 'ቦሌ ዋና ቅርንጫፍ',
        address: 'Bole Road, Near Edna Mall',
        city: 'Addis Ababa',
        phone: '+251911234568',
        isMainBranch: true,
        floors: [
          {
            name: 'Ground Floor — Main Hall',
            nameAm: 'መሬት ፎቅ — ዋና አዳራሽ',
            sortOrder: 1,
            width: 1600,
            height: 1000,
            walls: [
              { x1: 0, y1: 0, x2: 1600, y2: 0, thickness: 8 },
              { x1: 0, y1: 0, x2: 0, y2: 1000, thickness: 8 },
              { x1: 1600, y1: 0, x2: 1600, y2: 1000, thickness: 8 },
              { x1: 0, y1: 1000, x2: 1600, y2: 1000, thickness: 8 },
              { x1: 600, y1: 0, x2: 600, y2: 400, thickness: 6 },
              { x1: 1000, y1: 0, x2: 1000, y2: 400, thickness: 6 },
              { x1: 600, y1: 400, x2: 1000, y2: 400, thickness: 4 },
            ],
            obstacles: [
              { x: 20, y: 20, width: 160, height: 80, type: 'bar', label: 'Bar' },
              { x: 650, y: 20, width: 300, height: 120, type: 'kitchen', label: 'Kitchen' },
              { x: 1400, y: 20, width: 160, height: 100, type: 'stage', label: 'Stage' },
              { x: 20, y: 880, width: 120, height: 80, type: 'restroom', label: 'Restroom' },
              { x: 800, y: 880, width: 80, height: 80, type: 'plant', label: 'Plant' },
              { x: 1400, y: 880, width: 120, height: 80, type: 'entrance', label: 'Entrance' },
            ],
            tables: [
              { number: 'G1', capacity: 2, shape: 'round', positionX: 100, positionY: 200, width: 70, height: 70, status: 'available' },
              { number: 'G2', capacity: 4, shape: 'square', positionX: 220, positionY: 180, width: 80, height: 80, status: 'available' },
              { number: 'G3', capacity: 4, shape: 'square', positionX: 340, positionY: 180, width: 80, height: 80, status: 'occupied' },
              { number: 'G4', capacity: 6, shape: 'rectangle', positionX: 100, positionY: 350, width: 120, height: 80, status: 'available' },
              { number: 'G5', capacity: 8, shape: 'rectangle', positionX: 260, positionY: 340, width: 140, height: 90, status: 'reserved' },
              { number: 'G6', capacity: 2, shape: 'round', positionX: 450, positionY: 200, width: 70, height: 70, status: 'available' },
              { number: 'G7', capacity: 4, shape: 'oval', positionX: 700, positionY: 550, width: 110, height: 75, status: 'available' },
              { number: 'G8', capacity: 4, shape: 'square', positionX: 860, positionY: 550, width: 80, height: 80, status: 'occupied' },
              { number: 'G9', capacity: 6, shape: 'rectangle', positionX: 1050, positionY: 530, width: 120, height: 80, status: 'available' },
              { number: 'G10', capacity: 4, shape: 'square', positionX: 1200, positionY: 550, width: 80, height: 80, status: 'cleaning' },
              { number: 'G11', capacity: 2, shape: 'round', positionX: 1350, positionY: 200, width: 70, height: 70, status: 'available' },
              { number: 'G12', capacity: 10, shape: 'rectangle', positionX: 1100, positionY: 200, width: 160, height: 100, status: 'available' },
            ],
          },
          {
            name: 'Second Floor — VIP Lounge',
            nameAm: 'ሁለተኛ ፎቅ — ቪአይፒ',
            sortOrder: 2,
            width: 1400,
            height: 900,
            walls: [
              { x1: 0, y1: 0, x2: 1400, y2: 0, thickness: 8 },
              { x1: 0, y1: 0, x2: 0, y2: 900, thickness: 8 },
              { x1: 1400, y1: 0, x2: 1400, y2: 900, thickness: 8 },
              { x1: 0, y1: 900, x2: 1400, y2: 900, thickness: 8 },
              { x1: 700, y1: 0, x2: 700, y2: 300, thickness: 6 },
            ],
            obstacles: [
              { x: 20, y: 20, width: 150, height: 80, type: 'bar', label: 'VIP Bar' },
              { x: 720, y: 20, width: 250, height: 100, type: 'kitchen', label: 'Kitchen' },
              { x: 1200, y: 20, width: 140, height: 100, type: 'lounge', label: 'VIP Lounge' },
              { x: 1200, y: 780, width: 120, height: 80, type: 'restroom', label: 'Restroom' },
            ],
            tables: [
              { number: 'V1', capacity: 6, shape: 'rectangle', positionX: 100, positionY: 200, width: 120, height: 80, status: 'available' },
              { number: 'V2', capacity: 4, shape: 'round', positionX: 300, positionY: 200, width: 90, height: 90, status: 'reserved' },
              { number: 'V3', capacity: 8, shape: 'rectangle', positionX: 500, positionY: 180, width: 150, height: 100, status: 'available' },
              { number: 'V4', capacity: 4, shape: 'oval', positionX: 800, positionY: 400, width: 110, height: 75, status: 'occupied' },
              { number: 'V5', capacity: 2, shape: 'round', positionX: 1000, positionY: 400, width: 70, height: 70, status: 'available' },
              { number: 'V6', capacity: 6, shape: 'rectangle', positionX: 300, positionY: 500, width: 120, height: 80, status: 'available' },
            ],
          },
          {
            name: 'Rooftop Terrace',
            nameAm: 'ጣሪያ',
            sortOrder: 3,
            width: 1800,
            height: 600,
            walls: [
              { x1: 0, y1: 0, x2: 1800, y2: 0, thickness: 4 },
              { x1: 0, y1: 600, x2: 1800, y2: 600, thickness: 4 },
            ],
            obstacles: [
              { x: 20, y: 20, width: 200, height: 80, type: 'bar', label: 'Sky Bar' },
              { x: 800, y: 20, width: 200, height: 80, type: 'kitchen', label: 'Kitchen' },
              { x: 400, y: 450, width: 80, height: 80, type: 'plant', label: 'Garden' },
              { x: 1200, y: 450, width: 80, height: 80, type: 'plant', label: 'Garden' },
            ],
            tables: [
              { number: 'R1', capacity: 2, shape: 'round', positionX: 100, positionY: 200, width: 70, height: 70, status: 'available' },
              { number: 'R2', capacity: 4, shape: 'square', positionX: 250, positionY: 180, width: 80, height: 80, status: 'available' },
              { number: 'R3', capacity: 4, shape: 'square', positionX: 400, positionY: 180, width: 80, height: 80, status: 'occupied' },
              { number: 'R4', capacity: 2, shape: 'round', positionX: 550, positionY: 200, width: 70, height: 70, status: 'available' },
              { number: 'R5', capacity: 6, shape: 'rectangle', positionX: 700, positionY: 180, width: 120, height: 80, status: 'available' },
              { number: 'R6', capacity: 4, shape: 'square', positionX: 900, positionY: 200, width: 80, height: 80, status: 'reserved' },
              { number: 'R7', capacity: 8, shape: 'rectangle', positionX: 1050, positionY: 170, width: 150, height: 100, status: 'available' },
              { number: 'R8', capacity: 2, shape: 'round', positionX: 1300, positionY: 200, width: 70, height: 70, status: 'available' },
              { number: 'R9', capacity: 4, shape: 'oval', positionX: 1450, positionY: 180, width: 110, height: 75, status: 'available' },
            ],
          },
        ],
        kitchenStations: [
          { name: 'Wot Station', type: 'general', sortOrder: 1 },
          { name: 'Tibs & Grill', type: 'grill', sortOrder: 2 },
          { name: 'Drinks Bar', type: 'drinks', sortOrder: 3 },
          { name: 'Coffee Corner', type: 'dessert', sortOrder: 4 },
        ],
      },
      {
        id: 'branch-habesha-cmc',
        name: 'CMC Branch',
        nameAm: 'ሲኤምሲ ቅርንጫፍ',
        address: 'CMC Roundabout',
        city: 'Addis Ababa',
        phone: '+251911234569',
        isMainBranch: false,
        floors: [
          {
            name: 'Main Hall',
            nameAm: 'ዋና አዳራሽ',
            sortOrder: 1,
            width: 1200,
            height: 800,
            walls: [
              { x1: 0, y1: 0, x2: 1200, y2: 0, thickness: 8 },
              { x1: 0, y1: 0, x2: 0, y2: 800, thickness: 8 },
              { x1: 1200, y1: 0, x2: 1200, y2: 800, thickness: 8 },
              { x1: 0, y1: 800, x2: 1200, y2: 800, thickness: 8 },
            ],
            obstacles: [
              { x: 20, y: 20, width: 140, height: 70, type: 'bar', label: 'Bar' },
              { x: 500, y: 20, width: 200, height: 80, type: 'kitchen', label: 'Kitchen' },
              { x: 1000, y: 20, width: 140, height: 80, type: 'entrance', label: 'Entrance' },
            ],
            tables: [
              { number: '1', capacity: 4, shape: 'square', positionX: 100, positionY: 200, width: 80, height: 80, status: 'available' },
              { number: '2', capacity: 2, shape: 'round', positionX: 250, positionY: 220, width: 70, height: 70, status: 'available' },
              { number: '3', capacity: 6, shape: 'rectangle', positionX: 400, positionY: 200, width: 120, height: 80, status: 'occupied' },
              { number: '4', capacity: 4, shape: 'square', positionX: 600, positionY: 400, width: 80, height: 80, status: 'available' },
              { number: '5', capacity: 8, shape: 'rectangle', positionX: 800, positionY: 380, width: 150, height: 100, status: 'reserved' },
              { number: '6', capacity: 2, shape: 'round', positionX: 1000, positionY: 400, width: 70, height: 70, status: 'available' },
              { number: '7', capacity: 4, shape: 'oval', positionX: 200, positionY: 500, width: 110, height: 75, status: 'available' },
              { number: '8', capacity: 4, shape: 'square', positionX: 400, positionY: 550, width: 80, height: 80, status: 'cleaning' },
            ],
          },
        ],
        kitchenStations: [
          { name: 'Main Kitchen', type: 'general', sortOrder: 1 },
          { name: 'Drinks', type: 'drinks', sortOrder: 2 },
        ],
      },
    ],
    staff: [
      { name: 'Abebe Kebede', email: 'owner@habesha.et', phone: '+251911000001', role: 'owner' },
      { name: 'Tigist Haile', email: 'manager@habesha.et', phone: '+251911000002', role: 'manager' },
      { name: 'Dawit Amare', email: 'waiter@habesha.et', phone: '+251911000003', role: 'waiter' },
      { name: 'Mulugeta Tadesse', email: 'kitchen@habesha.et', phone: '+251911000004', role: 'kitchen_staff' },
      { name: 'Helen Gebre', email: 'cashier@habesha.et', phone: '+251911000005', role: 'cashier' },
    ],
  },
  {
    id: 'rest-blue-nile',
    slug: 'blue-nile-grill',
    name: 'Blue Nile Grill',
    nameAm: 'ሰማያዊ ናይል ግሪል',
    description: 'Upscale fusion restaurant blending Ethiopian flavors with contemporary international cuisine, featuring an extensive wine list and craft cocktails',
    descriptionAm: 'የኢትዮጵያ ጣዕም ከዘመናዊ አለም አቀፍ ምግብ ጋር የሚያዋህድ ምርጥ ሬስቶራንት',
    cuisineType: 'Ethiopian Fusion',
    phone: '+251922345678',
    email: 'info@bluenilegrill.et',
    address: 'Kazanchis, Africa Avenue',
    city: 'Addis Ababa',
    taxRate: 0.15,
    serviceCharge: 0.12,
    workingHours: '{"mon":{"open":"11:00","close":"23:00"},"tue":{"open":"11:00","close":"23:00"},"wed":{"open":"11:00","close":"23:00"},"thu":{"open":"11:00","close":"23:00"},"fri":{"open":"11:00","close":"00:00"},"sat":{"open":"10:00","close":"00:00"},"sun":{"open":"10:00","close":"22:00"}}',
    plan: 'plan-premium',
    branches: [
      {
        id: 'branch-bluenile-main',
        name: 'Kazanchis Main',
        nameAm: 'ካዛንቺስ ዋና',
        address: 'Kazanchis, Africa Avenue',
        city: 'Addis Ababa',
        phone: '+251922345679',
        isMainBranch: true,
        floors: [
          {
            name: 'Main Dining',
            nameAm: 'ዋና ክፍል',
            sortOrder: 1,
            width: 1400,
            height: 900,
            walls: [
              { x1: 0, y1: 0, x2: 1400, y2: 0, thickness: 8 },
              { x1: 0, y1: 0, x2: 0, y2: 900, thickness: 8 },
              { x1: 1400, y1: 0, x2: 1400, y2: 900, thickness: 8 },
              { x1: 0, y1: 900, x2: 1400, y2: 900, thickness: 8 },
              { x1: 500, y1: 0, x2: 500, y2: 300, thickness: 5 },
            ],
            obstacles: [
              { x: 20, y: 20, width: 200, height: 80, type: 'bar', label: 'Cocktail Bar' },
              { x: 520, y: 20, width: 250, height: 100, type: 'kitchen', label: 'Open Kitchen' },
              { x: 1200, y: 20, width: 140, height: 80, type: 'lounge', label: 'VIP' },
              { x: 20, y: 780, width: 120, height: 80, type: 'restroom', label: 'Restroom' },
              { x: 600, y: 780, width: 80, height: 60, type: 'plant', label: 'Plant' },
            ],
            tables: [
              { number: 'BN1', capacity: 2, shape: 'round', positionX: 80, positionY: 200, width: 70, height: 70, status: 'available' },
              { number: 'BN2', capacity: 4, shape: 'square', positionX: 200, positionY: 200, width: 80, height: 80, status: 'available' },
              { number: 'BN3', capacity: 4, shape: 'square', positionX: 350, positionY: 200, width: 80, height: 80, status: 'occupied' },
              { number: 'BN4', capacity: 6, shape: 'rectangle', positionX: 600, positionY: 400, width: 120, height: 80, status: 'available' },
              { number: 'BN5', capacity: 4, shape: 'oval', positionX: 800, positionY: 400, width: 110, height: 75, status: 'reserved' },
              { number: 'BN6', capacity: 2, shape: 'round', positionX: 1000, positionY: 400, width: 70, height: 70, status: 'available' },
              { number: 'BN7', capacity: 8, shape: 'rectangle', positionX: 1100, positionY: 200, width: 150, height: 100, status: 'available' },
              { number: 'BN8', capacity: 4, shape: 'square', positionX: 200, positionY: 500, width: 80, height: 80, status: 'available' },
              { number: 'BN9', capacity: 6, shape: 'rectangle', positionX: 400, positionY: 550, width: 120, height: 80, status: 'cleaning' },
              { number: 'BN10', capacity: 4, shape: 'square', positionX: 900, positionY: 600, width: 80, height: 80, status: 'available' },
            ],
          },
        ],
        kitchenStations: [
          { name: 'Fusion Kitchen', type: 'general', sortOrder: 1 },
          { name: 'Grill Station', type: 'grill', sortOrder: 2 },
          { name: 'Cocktail Bar', type: 'drinks', sortOrder: 3 },
          { name: 'Dessert Lab', type: 'dessert', sortOrder: 4 },
        ],
      },
    ],
    staff: [
      { name: 'Nahom Tesfaye', email: 'owner@bluenile.et', phone: '+251922000001', role: 'owner' },
      { name: 'Selamawit Girma', email: 'manager@bluenile.et', phone: '+251922000002', role: 'manager' },
      { name: 'Binyam Assefa', email: 'kitchen@bluenile.et', phone: '+251922000003', role: 'kitchen_staff' },
      { name: 'Frehiwot Bekele', email: 'waiter@bluenile.et', phone: '+251922000004', role: 'waiter' },
      { name: 'Yared Worku', email: 'cashier@bluenile.et', phone: '+251922000005', role: 'cashier' },
    ],
  },
  {
    id: 'rest-yod-abyssinia',
    slug: 'yod-abyssinia',
    name: 'Yod Abyssinia',
    nameAm: 'ዮድ አቢሲኒያ',
    description: 'Legendary cultural restaurant featuring traditional Azmari musicians, Eskista dancers, and the finest Ethiopian feasts served on grand mesobs',
    descriptionAm: 'ባህላዊ ዝማሬ እና የእስክስታ ጨዋታ በሚቀርብበት ታዋቂ ሬስቶራንት',
    cuisineType: 'Ethiopian Cultural',
    phone: '+251933456789',
    email: 'info@yodabyssinia.et',
    address: 'Sarbet, Near Teklehaimanot',
    city: 'Addis Ababa',
    taxRate: 0.15,
    serviceCharge: 0.15,
    plan: 'plan-pro',
    branches: [
      {
        id: 'branch-yod-main',
        name: 'Sarbet Cultural House',
        nameAm: 'ሳርቤት ባህላዊ ቤት',
        address: 'Sarbet, Near Teklehaimanot Church',
        city: 'Addis Ababa',
        phone: '+251933456780',
        isMainBranch: true,
        floors: [
          {
            name: 'Grand Hall',
            nameAm: 'ታላቅ አዳራሽ',
            sortOrder: 1,
            width: 2000,
            height: 1200,
            walls: [
              { x1: 0, y1: 0, x2: 2000, y2: 0, thickness: 10 },
              { x1: 0, y1: 0, x2: 0, y2: 1200, thickness: 10 },
              { x1: 2000, y1: 0, x2: 2000, y2: 1200, thickness: 10 },
              { x1: 0, y1: 1200, x2: 2000, y2: 1200, thickness: 10 },
              { x1: 800, y1: 0, x2: 800, y2: 500, thickness: 6 },
              { x1: 1200, y1: 0, x2: 1200, y2: 500, thickness: 6 },
            ],
            obstacles: [
              { x: 20, y: 20, width: 200, height: 100, type: 'bar', label: 'Tej Bet' },
              { x: 820, y: 20, width: 360, height: 130, type: 'kitchen', label: 'Grand Kitchen' },
              { x: 1700, y: 20, width: 200, height: 120, type: 'stage', label: 'Azmari Stage' },
              { x: 20, y: 1060, width: 140, height: 100, type: 'restroom', label: 'Restroom' },
              { x: 600, y: 1060, width: 100, height: 80, type: 'plant', label: 'Plant' },
              { x: 1800, y: 1060, width: 140, height: 100, type: 'entrance', label: 'Main Entrance' },
            ],
            tables: [
              { number: 'M1', capacity: 8, shape: 'round', positionX: 100, positionY: 250, width: 120, height: 120, status: 'available' },
              { number: 'M2', capacity: 6, shape: 'round', positionX: 300, positionY: 250, width: 100, height: 100, status: 'occupied' },
              { number: 'M3', capacity: 10, shape: 'round', positionX: 500, positionY: 230, width: 130, height: 130, status: 'reserved' },
              { number: 'M4', capacity: 8, shape: 'round', positionX: 100, positionY: 500, width: 120, height: 120, status: 'available' },
              { number: 'M5', capacity: 6, shape: 'round', positionX: 300, positionY: 500, width: 100, height: 100, status: 'available' },
              { number: 'M6', capacity: 12, shape: 'round', positionX: 500, positionY: 500, width: 140, height: 140, status: 'available' },
              { number: 'M7', capacity: 4, shape: 'square', positionX: 850, positionY: 600, width: 80, height: 80, status: 'available' },
              { number: 'M8', capacity: 4, shape: 'square', positionX: 1000, positionY: 600, width: 80, height: 80, status: 'occupied' },
              { number: 'M9', capacity: 6, shape: 'rectangle', positionX: 1200, positionY: 600, width: 120, height: 80, status: 'available' },
              { number: 'M10', capacity: 4, shape: 'square', positionX: 1400, positionY: 600, width: 80, height: 80, status: 'available' },
              { number: 'M11', capacity: 8, shape: 'round', positionX: 900, positionY: 850, width: 120, height: 120, status: 'available' },
              { number: 'M12', capacity: 6, shape: 'round', positionX: 1100, positionY: 850, width: 100, height: 100, status: 'reserved' },
              { number: 'M13', capacity: 4, shape: 'square', positionX: 1300, positionY: 850, width: 80, height: 80, status: 'available' },
              { number: 'M14', capacity: 2, shape: 'round', positionX: 1500, positionY: 300, width: 70, height: 70, status: 'available' },
            ],
          },
        ],
        kitchenStations: [
          { name: 'Wot Kitchen', type: 'general', sortOrder: 1 },
          { name: 'Tibs Grill', type: 'grill', sortOrder: 2 },
          { name: 'Tej & Drinks', type: 'drinks', sortOrder: 3 },
          { name: 'Injera Station', type: 'general', sortOrder: 4 },
        ],
      },
    ],
    staff: [
      { name: 'Aster Aweke', email: 'owner@yod.et', phone: '+251933000001', role: 'owner' },
      { name: 'Tilahun Gessesse', email: 'manager@yod.et', phone: '+251933000002', role: 'manager' },
      { name: 'Mahmoud Ahmed', email: 'kitchen@yod.et', phone: '+251933000003', role: 'kitchen_staff' },
      { name: 'Ejegayehu Shibabaw', email: 'waiter@yod.et', phone: '+251933000004', role: 'waiter' },
      { name: 'Hana Girma', email: 'cashier@yod.et', phone: '+251933000005', role: 'cashier' },
    ],
  },
  {
    id: 'rest-lalibela',
    slug: 'lalibela-restaurant',
    name: 'Lalibela Rock Restaurant',
    nameAm: 'ላሊበላ ድንጋይ ሬስቶራንት',
    description: 'A multi-story dining experience inspired by the rock-hewn churches, with each floor themed after a different Ethiopian region and its culinary traditions',
    descriptionAm: 'በላሊበላ ድንጋይ ቤተክርስቲያን የተመለከተ ባለብዙ-ፎቅ ምግብ ቤት',
    cuisineType: 'Ethiopian Regional',
    phone: '+251944567890',
    email: 'info@lalibela-restaurant.et',
    address: 'Megenagna Square',
    city: 'Addis Ababa',
    taxRate: 0.15,
    serviceCharge: 0.10,
    plan: 'plan-pro',
    branches: [
      {
        id: 'branch-lalibela-main',
        name: 'Megenagna Main',
        nameAm: 'መገናኛ ዋና',
        address: 'Megenagna Square, Building 5',
        city: 'Addis Ababa',
        phone: '+251944567891',
        isMainBranch: true,
        floors: [
          {
            name: '1F — Tigray Region',
            nameAm: '1ኛ ፎቅ — ትግራይ',
            sortOrder: 1,
            width: 1200,
            height: 800,
            walls: [
              { x1: 0, y1: 0, x2: 1200, y2: 0, thickness: 8 },
              { x1: 0, y1: 0, x2: 0, y2: 800, thickness: 8 },
              { x1: 1200, y1: 0, x2: 1200, y2: 800, thickness: 8 },
              { x1: 0, y1: 800, x2: 1200, y2: 800, thickness: 8 },
            ],
            obstacles: [
              { x: 20, y: 20, width: 160, height: 80, type: 'kitchen', label: 'Tigray Kitchen' },
              { x: 1000, y: 20, width: 140, height: 80, type: 'entrance', label: 'Entrance' },
              { x: 500, y: 650, width: 80, height: 80, type: 'plant', label: 'Olive Tree' },
            ],
            tables: [
              { number: 'T1', capacity: 4, shape: 'square', positionX: 100, positionY: 200, width: 80, height: 80, status: 'available' },
              { number: 'T2', capacity: 2, shape: 'round', positionX: 250, positionY: 220, width: 70, height: 70, status: 'available' },
              { number: 'T3', capacity: 6, shape: 'rectangle', positionX: 400, positionY: 200, width: 120, height: 80, status: 'occupied' },
              { number: 'T4', capacity: 4, shape: 'square', positionX: 600, positionY: 300, width: 80, height: 80, status: 'available' },
              { number: 'T5', capacity: 4, shape: 'square', positionX: 800, positionY: 300, width: 80, height: 80, status: 'reserved' },
              { number: 'T6', capacity: 2, shape: 'round', positionX: 1000, positionY: 300, width: 70, height: 70, status: 'available' },
            ],
          },
          {
            name: '2F — Oromia Region',
            nameAm: '2ኛ ፎቅ — ኦሮሚያ',
            sortOrder: 2,
            width: 1200,
            height: 800,
            walls: [
              { x1: 0, y1: 0, x2: 1200, y2: 0, thickness: 8 },
              { x1: 0, y1: 0, x2: 0, y2: 800, thickness: 8 },
              { x1: 1200, y1: 0, x2: 1200, y2: 800, thickness: 8 },
              { x1: 0, y1: 800, x2: 1200, y2: 800, thickness: 8 },
            ],
            obstacles: [
              { x: 20, y: 20, width: 160, height: 80, type: 'kitchen', label: 'Oromia Kitchen' },
              { x: 1000, y: 20, width: 140, height: 80, type: 'bar', label: 'Buna Bet' },
            ],
            tables: [
              { number: 'O1', capacity: 6, shape: 'rectangle', positionX: 150, positionY: 200, width: 120, height: 80, status: 'available' },
              { number: 'O2', capacity: 4, shape: 'round', positionX: 350, positionY: 220, width: 90, height: 90, status: 'available' },
              { number: 'O3', capacity: 8, shape: 'rectangle', positionX: 550, positionY: 180, width: 150, height: 100, status: 'available' },
              { number: 'O4', capacity: 4, shape: 'square', positionX: 800, positionY: 350, width: 80, height: 80, status: 'occupied' },
              { number: 'O5', capacity: 2, shape: 'round', positionX: 950, positionY: 350, width: 70, height: 70, status: 'available' },
            ],
          },
          {
            name: '3F — Gurage & South',
            nameAm: '3ኛ ፎቅ — ጉራጌ እና ደቡብ',
            sortOrder: 3,
            width: 1000,
            height: 700,
            walls: [
              { x1: 0, y1: 0, x2: 1000, y2: 0, thickness: 8 },
              { x1: 0, y1: 0, x2: 0, y2: 700, thickness: 8 },
              { x1: 1000, y1: 0, x2: 1000, y2: 700, thickness: 8 },
              { x1: 0, y1: 700, x2: 1000, y2: 700, thickness: 8 },
            ],
            obstacles: [
              { x: 20, y: 20, width: 150, height: 80, type: 'kitchen', label: 'Gurage Kitchen' },
              { x: 800, y: 20, width: 140, height: 80, type: 'lounge', label: 'VIP' },
            ],
            tables: [
              { number: 'G1', capacity: 4, shape: 'square', positionX: 150, positionY: 200, width: 80, height: 80, status: 'available' },
              { number: 'G2', capacity: 6, shape: 'rectangle', positionX: 350, positionY: 200, width: 120, height: 80, status: 'reserved' },
              { number: 'G3', capacity: 4, shape: 'square', positionX: 550, positionY: 350, width: 80, height: 80, status: 'available' },
              { number: 'G4', capacity: 2, shape: 'round', positionX: 750, positionY: 350, width: 70, height: 70, status: 'occupied' },
            ],
          },
        ],
        kitchenStations: [
          { name: 'Tigray Kitchen', type: 'general', sortOrder: 1 },
          { name: 'Oromia Kitchen', type: 'general', sortOrder: 2 },
          { name: 'Grill Station', type: 'grill', sortOrder: 3 },
          { name: 'Coffee Ceremony', type: 'drinks', sortOrder: 4 },
        ],
      },
    ],
    staff: [
      { name: 'Gebremeskel Tadesse', email: 'owner@lalibela.et', phone: '+251944000001', role: 'owner' },
      { name: 'Fantaye Belay', email: 'manager@lalibela.et', phone: '+251944000002', role: 'manager' },
      { name: 'Beletech Arega', email: 'waiter@lalibela.et', phone: '+251944000003', role: 'waiter' },
      { name: 'Kiros Abebe', email: 'kitchen@lalibela.et', phone: '+251944000004', role: 'kitchen_staff' },
      { name: 'Tsehay Tuji', email: 'cashier@lalibela.et', phone: '+251944000005', role: 'cashier' },
    ],
  },
  {
    id: 'rest-sheba-lounge',
    slug: 'sheba-lounge',
    name: 'Sheba Lounge & Bar',
    nameAm: 'ሳባ ላውንጅ እና ባር',
    description: 'Chic modern lounge specializing in Ethiopian-inspired craft cocktails, premium spirits, and gourmet bar bites with live jazz on weekends',
    descriptionAm: 'ዘመናዊ የኢትዮጵያ ኮክቴል እና ጥራት ያለው ባር',
    cuisineType: 'Ethiopian Modern Bar',
    phone: '+251955678901',
    email: 'info@shebalounge.et',
    address: 'Gerji, Near Bethlehem',
    city: 'Addis Ababa',
    taxRate: 0.15,
    serviceCharge: 0.15,
    plan: 'plan-pro',
    branches: [
      {
        id: 'branch-sheba-main',
        name: 'Gerji Main',
        nameAm: 'ገርጂ ዋና',
        address: 'Gerji, Near Bethlehem Hospital',
        city: 'Addis Ababa',
        phone: '+251955678902',
        isMainBranch: true,
        floors: [
          {
            name: 'Lounge Floor',
            nameAm: 'ላውንጅ ፎቅ',
            sortOrder: 1,
            width: 1000,
            height: 700,
            walls: [
              { x1: 0, y1: 0, x2: 1000, y2: 0, thickness: 6 },
              { x1: 0, y1: 0, x2: 0, y2: 700, thickness: 6 },
              { x1: 1000, y1: 0, x2: 1000, y2: 700, thickness: 6 },
              { x1: 0, y1: 700, x2: 1000, y2: 700, thickness: 6 },
            ],
            obstacles: [
              { x: 300, y: 20, width: 400, height: 80, type: 'bar', label: 'Main Bar' },
              { x: 20, y: 20, width: 120, height: 60, type: 'stage', label: 'Jazz Stage' },
              { x: 850, y: 20, width: 100, height: 60, type: 'kitchen', label: 'Kitchen' },
            ],
            tables: [
              { number: 'S1', capacity: 2, shape: 'round', positionX: 50, positionY: 200, width: 60, height: 60, status: 'available' },
              { number: 'S2', capacity: 2, shape: 'round', positionX: 170, positionY: 200, width: 60, height: 60, status: 'occupied' },
              { number: 'S3', capacity: 4, shape: 'square', positionX: 50, positionY: 350, width: 80, height: 80, status: 'available' },
              { number: 'S4', capacity: 4, shape: 'square', positionX: 200, positionY: 350, width: 80, height: 80, status: 'reserved' },
              { number: 'S5', capacity: 6, shape: 'rectangle', positionX: 400, positionY: 300, width: 120, height: 80, status: 'available' },
              { number: 'S6', capacity: 2, shape: 'round', positionX: 600, positionY: 350, width: 60, height: 60, status: 'available' },
              { number: 'S7', capacity: 4, shape: 'oval', positionX: 750, positionY: 300, width: 110, height: 75, status: 'available' },
              { number: 'S8', capacity: 2, shape: 'round', positionX: 900, positionY: 350, width: 60, height: 60, status: 'occupied' },
            ],
          },
        ],
        kitchenStations: [
          { name: 'Bar Station', type: 'drinks', sortOrder: 1 },
          { name: 'Kitchen', type: 'general', sortOrder: 2 },
        ],
      },
    ],
    staff: [
      { name: 'Sara Nega', email: 'owner@sheba.et', phone: '+251955000001', role: 'owner' },
      { name: 'Feven Tadesse', email: 'manager@sheba.et', phone: '+251955000006', role: 'manager' },
      { name: 'Kidist Mamo', email: 'waiter@sheba.et', phone: '+251955000002', role: 'waiter' },
      { name: 'Solomon Bekele', email: 'kitchen@sheba.et', phone: '+251955000003', role: 'kitchen_staff' },
      { name: 'Mekdes Hailu', email: 'cashier@sheba.et', phone: '+251955000004', role: 'cashier' },
    ],
  },
  {
    id: 'rest-meskel-cafe',
    slug: 'meskel-cafe',
    name: 'Meskel Coffee House',
    nameAm: 'መስቀል ቡና ቤት',
    description: 'Artisan Ethiopian coffee house featuring single-origin beans from Yirgacheffe, Sidamo, and Harrar, with traditional coffee ceremony and fresh pastries',
    descriptionAm: 'ከይርጋጨፌ፣ ሲዳሞ እና ሐረር የተገኙ ጥራት ያላቸው የኢትዮጵያ ቡና ፍሬዎች',
    cuisineType: 'Ethiopian Coffee & Pastry',
    phone: '+251966789012',
    email: 'info@meskelcoffee.et',
    address: 'Piazza, Near St. George Church',
    city: 'Addis Ababa',
    taxRate: 0.15,
    serviceCharge: 0.05,
    plan: 'plan-basic',
    branches: [
      {
        id: 'branch-meskel-main',
        name: 'Piazza Original',
        nameAm: 'ፒያሳ መቀድሚያ',
        address: 'Piazza, Near St. George Church',
        city: 'Addis Ababa',
        phone: '+251966789013',
        isMainBranch: true,
        floors: [
          {
            name: 'Coffee Hall',
            nameAm: 'ቡና ክፍል',
            sortOrder: 1,
            width: 800,
            height: 600,
            walls: [
              { x1: 0, y1: 0, x2: 800, y2: 0, thickness: 6 },
              { x1: 0, y1: 0, x2: 0, y2: 600, thickness: 6 },
              { x1: 800, y1: 0, x2: 800, y2: 600, thickness: 6 },
              { x1: 0, y1: 600, x2: 800, y2: 600, thickness: 6 },
            ],
            obstacles: [
              { x: 300, y: 20, width: 200, height: 60, type: 'bar', label: 'Coffee Bar' },
              { x: 20, y: 20, width: 100, height: 60, type: 'kitchen', label: 'Pastry' },
              { x: 650, y: 20, width: 100, height: 60, type: 'entrance', label: 'Door' },
            ],
            tables: [
              { number: 'C1', capacity: 2, shape: 'round', positionX: 60, positionY: 200, width: 60, height: 60, status: 'occupied' },
              { number: 'C2', capacity: 2, shape: 'round', positionX: 180, positionY: 200, width: 60, height: 60, status: 'available' },
              { number: 'C3', capacity: 4, shape: 'square', positionX: 60, positionY: 350, width: 80, height: 80, status: 'available' },
              { number: 'C4', capacity: 2, shape: 'round', positionX: 400, positionY: 300, width: 60, height: 60, status: 'available' },
              { number: 'C5', capacity: 4, shape: 'square', positionX: 550, positionY: 300, width: 80, height: 80, status: 'available' },
              { number: 'C6', capacity: 2, shape: 'round', positionX: 680, positionY: 300, width: 60, height: 60, status: 'reserved' },
            ],
          },
        ],
        kitchenStations: [
          { name: 'Coffee Station', type: 'drinks', sortOrder: 1 },
          { name: 'Pastry Kitchen', type: 'dessert', sortOrder: 2 },
        ],
      },
    ],
    staff: [
      { name: 'Alemayehu Desta', email: 'owner@meskel.et', phone: '+251966000001', role: 'owner' },
      { name: 'Roman Kassahun', email: 'manager@meskel.et', phone: '+251966000006', role: 'manager' },
      { name: 'Worknesh Tadesse', email: 'waiter@meskel.et', phone: '+251966000002', role: 'waiter' },
      { name: 'Dagnachew Asfaw', email: 'kitchen@meskel.et', phone: '+251966000003', role: 'kitchen_staff' },
      { name: 'Selam Teshome', email: 'cashier@meskel.et', phone: '+251966000004', role: 'cashier' },
    ],
  },
  {
    id: 'rest-aster-kitchen',
    slug: 'aster-kitchen',
    name: 'Aster\'s Kitchen',
    nameAm: 'አስቴር ኩሽና',
    description: 'Cozy neighborhood eatery serving home-style Ethiopian comfort food — the kind Aster\'s grandmother used to make, with recipes passed down for generations',
    descriptionAm: 'የቤት ውስጥ ምግብ የሚያቀርብ ሞቅ ያለ ሬስቶራንት',
    cuisineType: 'Ethiopian Home-style',
    phone: '+251977890123',
    email: 'info@asterkitchen.et',
    address: 'Kolfe, Near Ayat',
    city: 'Addis Ababa',
    taxRate: 0.15,
    serviceCharge: 0.0,
    plan: 'plan-basic',
    branches: [
      {
        id: 'branch-aster-main',
        name: 'Kolfe Branch',
        nameAm: 'ቆልፌ ቅርንጫፍ',
        address: 'Kolfe, Ayat Area',
        city: 'Addis Ababa',
        phone: '+251977890124',
        isMainBranch: true,
        floors: [
          {
            name: 'Dining Room',
            nameAm: 'ምግብ ክፍል',
            sortOrder: 1,
            width: 900,
            height: 650,
            walls: [
              { x1: 0, y1: 0, x2: 900, y2: 0, thickness: 6 },
              { x1: 0, y1: 0, x2: 0, y2: 650, thickness: 6 },
              { x1: 900, y1: 0, x2: 900, y2: 650, thickness: 6 },
              { x1: 0, y1: 650, x2: 900, y2: 650, thickness: 6 },
            ],
            obstacles: [
              { x: 20, y: 20, width: 120, height: 60, type: 'kitchen', label: 'Kitchen' },
              { x: 700, y: 20, width: 140, height: 60, type: 'entrance', label: 'Entrance' },
            ],
            tables: [
              { number: 'A1', capacity: 4, shape: 'square', positionX: 100, positionY: 200, width: 80, height: 80, status: 'available' },
              { number: 'A2', capacity: 4, shape: 'square', positionX: 250, positionY: 200, width: 80, height: 80, status: 'occupied' },
              { number: 'A3', capacity: 6, shape: 'rectangle', positionX: 450, positionY: 200, width: 120, height: 80, status: 'available' },
              { number: 'A4', capacity: 2, shape: 'round', positionX: 100, positionY: 400, width: 70, height: 70, status: 'available' },
              { number: 'A5', capacity: 4, shape: 'square', positionX: 300, positionY: 400, width: 80, height: 80, status: 'reserved' },
            ],
          },
        ],
        kitchenStations: [
          { name: 'Main Kitchen', type: 'general', sortOrder: 1 },
        ],
      },
    ],
    staff: [
      { name: 'Aster Bekele', email: 'owner@aster.et', phone: '+251977000001', role: 'owner' },
      { name: 'Birtukan Godefa', email: 'manager@aster.et', phone: '+251977000006', role: 'manager' },
      { name: 'Marta Hailu', email: 'kitchen@aster.et', phone: '+251977000002', role: 'kitchen_staff' },
      { name: 'Genet Alemu', email: 'waiter@aster.et', phone: '+251977000003', role: 'waiter' },
      { name: 'Mulu Ayele', email: 'cashier@aster.et', phone: '+251977000004', role: 'cashier' },
    ],
  },
  {
    id: 'rest-rift-valley',
    slug: 'rift-valley-fish',
    name: 'Rift Valley Fish House',
    nameAm: 'ረፍት ሸለቆ ዓሳ ቤት',
    description: 'Specialty seafood restaurant featuring fresh catches from Lake Langano and Lake Ziway, prepared with Ethiopian spices and served with local injera',
    descriptionAm: 'ከላንጋኖ እና ዚዋይ ሀይቅ የተያዙ አዳዲስ ዓሳዎች',
    cuisineType: 'Ethiopian Seafood',
    phone: '+251988901234',
    email: 'info@riftvalleyfish.et',
    address: 'Lebu, Near Tor Hailoch',
    city: 'Addis Ababa',
    taxRate: 0.15,
    serviceCharge: 0.10,
    plan: 'plan-pro',
    branches: [
      {
        id: 'branch-rift-main',
        name: 'Lebu Main',
        nameAm: 'ሌቡ ዋና',
        address: 'Lebu, Near Tor Hailoch',
        city: 'Addis Ababa',
        phone: '+251988901235',
        isMainBranch: true,
        floors: [
          {
            name: 'Lake View Hall',
            nameAm: 'የሀይቅ እይታ አዳራሽ',
            sortOrder: 1,
            width: 1300,
            height: 850,
            walls: [
              { x1: 0, y1: 0, x2: 1300, y2: 0, thickness: 8 },
              { x1: 0, y1: 0, x2: 0, y2: 850, thickness: 8 },
              { x1: 1300, y1: 0, x2: 1300, y2: 850, thickness: 8 },
              { x1: 0, y1: 850, x2: 1300, y2: 850, thickness: 8 },
            ],
            obstacles: [
              { x: 20, y: 20, width: 200, height: 80, type: 'bar', label: 'Bar' },
              { x: 500, y: 20, width: 300, height: 80, type: 'kitchen', label: 'Fish Kitchen' },
              { x: 1100, y: 700, width: 140, height: 80, type: 'entrance', label: 'Entrance' },
              { x: 20, y: 700, width: 100, height: 80, type: 'restroom', label: 'Restroom' },
            ],
            tables: [
              { number: 'F1', capacity: 4, shape: 'square', positionX: 100, positionY: 250, width: 80, height: 80, status: 'available' },
              { number: 'F2', capacity: 6, shape: 'rectangle', positionX: 300, positionY: 250, width: 120, height: 80, status: 'occupied' },
              { number: 'F3', capacity: 4, shape: 'square', positionX: 500, positionY: 300, width: 80, height: 80, status: 'available' },
              { number: 'F4', capacity: 2, shape: 'round', positionX: 680, positionY: 300, width: 70, height: 70, status: 'available' },
              { number: 'F5', capacity: 8, shape: 'rectangle', positionX: 800, positionY: 250, width: 150, height: 100, status: 'reserved' },
              { number: 'F6', capacity: 4, shape: 'oval', positionX: 200, positionY: 500, width: 110, height: 75, status: 'available' },
              { number: 'F7', capacity: 4, shape: 'square', positionX: 450, positionY: 500, width: 80, height: 80, status: 'available' },
              { number: 'F8', capacity: 6, shape: 'rectangle', positionX: 700, positionY: 500, width: 120, height: 80, status: 'cleaning' },
            ],
          },
        ],
        kitchenStations: [
          { name: 'Fish Prep', type: 'general', sortOrder: 1 },
          { name: 'Grill Station', type: 'grill', sortOrder: 2 },
          { name: 'Drinks', type: 'drinks', sortOrder: 3 },
        ],
      },
    ],
    staff: [
      { name: 'Tadesse Alemu', email: 'owner@riftvalley.et', phone: '+251988000001', role: 'owner' },
      { name: 'Abezash Demissie', email: 'manager@riftvalley.et', phone: '+251988000002', role: 'manager' },
      { name: 'Debebe Eshetu', email: 'kitchen@riftvalley.et', phone: '+251988000003', role: 'kitchen_staff' },
      { name: 'Chaltu Badhasa', email: 'waiter@riftvalley.et', phone: '+251988000004', role: 'waiter' },
      { name: 'Kebede Gutema', email: 'cashier@riftvalley.et', phone: '+251988000005', role: 'cashier' },
    ],
  },
  {
    id: 'rest-harar-gate',
    slug: 'harar-gate',
    name: 'Harar Gate Restaurant',
    nameAm: 'ሐረር መግቢያ ሬስቶራንት',
    description: 'An oasis of Harari and Eastern Ethiopian cuisine featuring the legendary Harari spice blends, fresh chat-free dining, and the city\'s best Fahita and Suhoor menu',
    descriptionAm: 'የሐረሪ እና ምስራቅ ኢትዮጵያ ምግቦች',
    cuisineType: 'Harari & Eastern Ethiopian',
    phone: '+251990123456',
    email: 'info@harargate.et',
    address: 'Merkato, Near Teklehaimanot',
    city: 'Addis Ababa',
    taxRate: 0.15,
    serviceCharge: 0.08,
    plan: 'plan-pro',
    branches: [
      {
        id: 'branch-harar-main',
        name: 'Merkato Branch',
        nameAm: 'መርካቶ ቅርንጫፍ',
        address: 'Merkato, Near Teklehaimanot Square',
        city: 'Addis Ababa',
        phone: '+251990123457',
        isMainBranch: true,
        floors: [
          {
            name: 'Harari Hall',
            nameAm: 'ሐረሪ አዳራሽ',
            sortOrder: 1,
            width: 1100,
            height: 750,
            walls: [
              { x1: 0, y1: 0, x2: 1100, y2: 0, thickness: 8 },
              { x1: 0, y1: 0, x2: 0, y2: 750, thickness: 8 },
              { x1: 1100, y1: 0, x2: 1100, y2: 750, thickness: 8 },
              { x1: 0, y1: 750, x2: 1100, y2: 750, thickness: 8 },
            ],
            obstacles: [
              { x: 20, y: 20, width: 140, height: 60, type: 'kitchen', label: 'Harari Kitchen' },
              { x: 900, y: 20, width: 140, height: 60, type: 'bar', label: 'Suhoor Bar' },
              { x: 500, y: 630, width: 80, height: 60, type: 'plant', label: 'Plant' },
            ],
            tables: [
              { number: 'H1', capacity: 4, shape: 'square', positionX: 100, positionY: 200, width: 80, height: 80, status: 'available' },
              { number: 'H2', capacity: 4, shape: 'square', positionX: 250, positionY: 200, width: 80, height: 80, status: 'available' },
              { number: 'H3', capacity: 6, shape: 'rectangle', positionX: 450, positionY: 200, width: 120, height: 80, status: 'occupied' },
              { number: 'H4', capacity: 2, shape: 'round', positionX: 650, positionY: 250, width: 70, height: 70, status: 'available' },
              { number: 'H5', capacity: 4, shape: 'oval', positionX: 800, positionY: 350, width: 110, height: 75, status: 'reserved' },
              { number: 'H6', capacity: 4, shape: 'square', positionX: 200, positionY: 450, width: 80, height: 80, status: 'available' },
              { number: 'H7', capacity: 6, shape: 'rectangle', positionX: 450, positionY: 430, width: 120, height: 80, status: 'available' },
            ],
          },
        ],
        kitchenStations: [
          { name: 'Harari Kitchen', type: 'general', sortOrder: 1 },
          { name: 'Grill', type: 'grill', sortOrder: 2 },
          { name: 'Drinks', type: 'drinks', sortOrder: 3 },
        ],
      },
    ],
    staff: [
      { name: 'Abdulahi Mohammed', email: 'owner@harargate.et', phone: '+251990000001', role: 'owner' },
      { name: 'Fatima Osman', email: 'manager@harargate.et', phone: '+251990000002', role: 'manager' },
      { name: 'Yusuf Adem', email: 'waiter@harargate.et', phone: '+251990000003', role: 'waiter' },
      { name: 'Hassan Jemal', email: 'kitchen@harargate.et', phone: '+251990000004', role: 'kitchen_staff' },
      { name: 'Amina Abdi', email: 'cashier@harargate.et', phone: '+251990000005', role: 'cashier' },
    ],
  },
  {
    id: 'rest-entsoto',
    slug: 'entsoto-terrace',
    name: 'Entoto Terrace',
    nameAm: 'እንጦጦ ቴራስ',
    description: 'Hilltop restaurant on Entoto Mountain with breathtaking views of Addis Ababa, serving organic farm-to-table Ethiopian cuisine with herbs from our own garden',
    descriptionAm: 'ከእንጦጦ ተራራ ላይ የሚታይ አስደናቂ እይታ ያለው ኦርጋኒክ ምግብ ቤት',
    cuisineType: 'Ethiopian Organic Farm-to-Table',
    phone: '+251901234567',
    email: 'info@entototerrace.et',
    address: 'Entoto Mountain, Near St. Mary Church',
    city: 'Addis Ababa',
    taxRate: 0.15,
    serviceCharge: 0.12,
    plan: 'plan-premium',
    branches: [
      {
        id: 'branch-entsoto-main',
        name: 'Mountain Top',
        nameAm: 'ተራራ ላይ',
        address: 'Entoto Mountain, Near St. Mary Church',
        city: 'Addis Ababa',
        phone: '+251901234568',
        isMainBranch: true,
        floors: [
          {
            name: 'Panorama Deck',
            nameAm: 'ፓኖራማ ደረጃ',
            sortOrder: 1,
            width: 1500,
            height: 800,
            walls: [
              { x1: 0, y1: 0, x2: 1500, y2: 0, thickness: 4 },
              { x1: 0, y1: 800, x2: 1500, y2: 800, thickness: 4 },
              { x1: 0, y1: 0, x2: 0, y2: 800, thickness: 8 },
              { x1: 1500, y1: 0, x2: 1500, y2: 800, thickness: 8 },
            ],
            obstacles: [
              { x: 20, y: 20, width: 180, height: 80, type: 'bar', label: 'Mountain Bar' },
              { x: 600, y: 20, width: 300, height: 80, type: 'kitchen', label: 'Organic Kitchen' },
              { x: 400, y: 600, width: 80, height: 80, type: 'plant', label: 'Herb Garden' },
              { x: 700, y: 600, width: 80, height: 80, type: 'plant', label: 'Herb Garden' },
              { x: 1000, y: 600, width: 80, height: 80, type: 'plant', label: 'Herb Garden' },
              { x: 1300, y: 600, width: 140, height: 80, type: 'entrance', label: 'Entrance' },
            ],
            tables: [
              { number: 'E1', capacity: 2, shape: 'round', positionX: 80, positionY: 250, width: 70, height: 70, status: 'available' },
              { number: 'E2', capacity: 4, shape: 'square', positionX: 200, positionY: 230, width: 80, height: 80, status: 'available' },
              { number: 'E3', capacity: 4, shape: 'square', positionX: 350, positionY: 230, width: 80, height: 80, status: 'occupied' },
              { number: 'E4', capacity: 6, shape: 'rectangle', positionX: 550, positionY: 300, width: 120, height: 80, status: 'available' },
              { number: 'E5', capacity: 4, shape: 'oval', positionX: 750, positionY: 300, width: 110, height: 75, status: 'reserved' },
              { number: 'E6', capacity: 2, shape: 'round', positionX: 950, positionY: 300, width: 70, height: 70, status: 'available' },
              { number: 'E7', capacity: 8, shape: 'rectangle', positionX: 1100, positionY: 230, width: 150, height: 100, status: 'available' },
              { number: 'E8', capacity: 4, shape: 'square', positionX: 200, positionY: 450, width: 80, height: 80, status: 'available' },
              { number: 'E9', capacity: 6, shape: 'rectangle', positionX: 500, positionY: 430, width: 120, height: 80, status: 'cleaning' },
            ],
          },
        ],
        kitchenStations: [
          { name: 'Organic Kitchen', type: 'general', sortOrder: 1 },
          { name: 'Herb Garden Bar', type: 'drinks', sortOrder: 2 },
          { name: 'Dessert Station', type: 'dessert', sortOrder: 3 },
        ],
      },
    ],
    staff: [
      { name: 'Mekdes Alemayehu', email: 'owner@entoto.et', phone: '+251901000001', role: 'owner' },
      { name: 'Biruk Tafesse', email: 'manager@entoto.et', phone: '+251901000006', role: 'manager' },
      { name: 'Yonas Teshome', email: 'kitchen@entoto.et', phone: '+251901000002', role: 'kitchen_staff' },
      { name: 'Hiwot Girma', email: 'waiter@entoto.et', phone: '+251901000003', role: 'waiter' },
      { name: 'Tigist Molla', email: 'cashier@entoto.et', phone: '+251901000004', role: 'cashier' },
    ],
  },
  {
    id: 'rest-wolkite-queen',
    slug: 'wolkite-queen',
    name: 'Wolkite Queen',
    nameAm: 'ወልቂቴ ንግሥት',
    description: 'A celebration of Southern Ethiopian and Gurage culinary heritage — featuring the famous Kocho, Kitfo, and unique spice blends from the fertile Gurage Zone',
    descriptionAm: 'የጉራጌ ዞን ልዩ ምግቦች ኮቾ፣ ክፍቶ እና ቅመማ ቅመም',
    cuisineType: 'Gurage & Southern Ethiopian',
    phone: '+251912345678',
    email: 'info@wolkitequeen.et',
    address: 'Jemo, Near Fana Broadcasting',
    city: 'Addis Ababa',
    taxRate: 0.15,
    serviceCharge: 0.08,
    plan: 'plan-basic',
    branches: [
      {
        id: 'branch-wolkite-main',
        name: 'Jemo Branch',
        nameAm: 'ጀሞ ቅርንጫፍ',
        address: 'Jemo, Near Fana Broadcasting Corporate',
        city: 'Addis Ababa',
        phone: '+251912345679',
        isMainBranch: true,
        floors: [
          {
            name: 'Dining Floor',
            nameAm: 'ምግብ ፎቅ',
            sortOrder: 1,
            width: 1000,
            height: 700,
            walls: [
              { x1: 0, y1: 0, x2: 1000, y2: 0, thickness: 6 },
              { x1: 0, y1: 0, x2: 0, y2: 700, thickness: 6 },
              { x1: 1000, y1: 0, x2: 1000, y2: 700, thickness: 6 },
              { x1: 0, y1: 700, x2: 1000, y2: 700, thickness: 6 },
            ],
            obstacles: [
              { x: 20, y: 20, width: 130, height: 60, type: 'kitchen', label: 'Kitchen' },
              { x: 800, y: 20, width: 130, height: 60, type: 'entrance', label: 'Door' },
            ],
            tables: [
              { number: 'W1', capacity: 4, shape: 'square', positionX: 100, positionY: 200, width: 80, height: 80, status: 'available' },
              { number: 'W2', capacity: 4, shape: 'square', positionX: 250, positionY: 200, width: 80, height: 80, status: 'occupied' },
              { number: 'W3', capacity: 6, shape: 'rectangle', positionX: 450, positionY: 200, width: 120, height: 80, status: 'available' },
              { number: 'W4', capacity: 2, shape: 'round', positionX: 650, positionY: 250, width: 70, height: 70, status: 'available' },
              { number: 'W5', capacity: 4, shape: 'oval', positionX: 200, positionY: 420, width: 110, height: 75, status: 'reserved' },
              { number: 'W6', capacity: 4, shape: 'square', positionX: 500, positionY: 400, width: 80, height: 80, status: 'available' },
            ],
          },
        ],
        kitchenStations: [
          { name: 'Main Kitchen', type: 'general', sortOrder: 1 },
          { name: 'Drinks', type: 'drinks', sortOrder: 2 },
        ],
      },
    ],
    staff: [
      { name: 'Zewdnesh Tadesse', email: 'owner@wolkite.et', phone: '+251912000001', role: 'owner' },
      { name: 'Eyasu Berhanu', email: 'manager@wolkite.et', phone: '+251912000006', role: 'manager' },
      { name: 'Endale Zeleke', email: 'kitchen@wolkite.et', phone: '+251912000002', role: 'kitchen_staff' },
      { name: 'Aster Chane', email: 'waiter@wolkite.et', phone: '+251912000003', role: 'waiter' },
      { name: 'Dinknesh Fikadu', email: 'cashier@wolkite.et', phone: '+251912000004', role: 'cashier' },
    ],
  },
];
