// ⚠️ DEPRECATED — This file contains mock/fallback data that is no longer actively used.
// Real data is now fetched from APIs. This file is kept temporarily for any remaining references
// and will be removed in a future cleanup.

import type { Category, MenuItem } from './customer-store'

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-appetizers',
    nameEn: 'Appetizers',
    nameAm: 'መክሰስ',
    emoji: '🥗',
  },
  {
    id: 'cat-mains',
    nameEn: 'Main Course',
    nameAm: 'ዋና ምግብ',
    emoji: '🍖',
  },
  {
    id: 'cat-drinks',
    nameEn: 'Drinks',
    nameAm: 'መጠጥ',
    emoji: '🍹',
  },
  {
    id: 'cat-desserts',
    nameEn: 'Desserts',
    nameAm: 'ፍሬ',
    emoji: '🍯',
  },
]

export const MOCK_MENU_ITEMS: MenuItem[] = [
  // Appetizers
  {
    id: 'item-shiro',
    nameEn: 'Shiro Wot',
    nameAm: 'ሽሮ ወጥ',
    descriptionEn: 'Smooth chickpea flour stew with berbere spices and garlic, a beloved Ethiopian comfort dish.',
    descriptionAm: 'በበርበሬ ቅመም እና ነጭ ሽንኩርት የተሰራ ለስላሳ የኑግ ዱቄት ወጥ።',
    price: 120,
    categoryId: 'cat-appetizers',
    emoji: '🍲',
    imageColor: '#D4A574',
    isVegetarian: true,
    isSpicy: true,
    isAvailable: true,
    modifiers: [
      {
        id: 'mod-shiro-spice',
        nameEn: 'Spice Level',
        nameAm: 'ቅመም ደረጃ',
        required: true,
        singleSelect: true,
        options: [
          { id: 'opt-mild', nameEn: 'Mild', nameAm: 'ያልተቀመመ', price: 0 },
          { id: 'opt-medium', nameEn: 'Medium', nameAm: 'መካከለኛ', price: 0 },
          { id: 'opt-hot', nameEn: 'Hot', nameAm: 'መራራ', price: 0 },
        ],
      },
      {
        id: 'mod-shiro-size',
        nameEn: 'Size',
        nameAm: 'መጠን',
        required: true,
        singleSelect: true,
        options: [
          { id: 'opt-small', nameEn: 'Small', nameAm: 'ትንሽ', price: 0 },
          { id: 'opt-medium-size', nameEn: 'Medium', nameAm: 'መካከለኛ', price: 30 },
          { id: 'opt-large', nameEn: 'Large', nameAm: 'ትልቅ', price: 60 },
        ],
      },
    ],
    addons: [
      { id: 'addon-injera-shiro', nameEn: 'Extra Injera', nameAm: 'ተጨማሪ እንጀራ', price: 25 },
      { id: 'addon-kitfo-shiro', nameEn: 'Side Kitfo', nameAm: 'ኪትፎ አጋር', price: 80 },
    ],
  },
  {
    id: 'item-tikil-gomen',
    nameEn: 'Tikil Gomen',
    nameAm: 'ጥቅል ጎመን',
    descriptionEn: 'Cabbage and potato stew with turmeric and carrots, a mild and satisfying vegetarian dish.',
    descriptionAm: 'በእርድ እና ካሮት የተሰራ የጎመን እና ድንች ወጥ።',
    price: 100,
    categoryId: 'cat-appetizers',
    emoji: '🥬',
    imageColor: '#A8D5A2',
    isVegetarian: true,
    isSpicy: false,
    isAvailable: true,
    modifiers: [
      {
        id: 'mod-gomen-size',
        nameEn: 'Size',
        nameAm: 'መጠን',
        required: true,
        singleSelect: true,
        options: [
          { id: 'opt-gomen-small', nameEn: 'Small', nameAm: 'ትንሽ', price: 0 },
          { id: 'opt-gomen-medium', nameEn: 'Medium', nameAm: 'መካከለኛ', price: 25 },
          { id: 'opt-gomen-large', nameEn: 'Large', nameAm: 'ትልቅ', price: 50 },
        ],
      },
    ],
    addons: [
      { id: 'addon-injera-gomen', nameEn: 'Extra Injera', nameAm: 'ተጨማሪ እንጀራ', price: 25 },
    ],
  },
  {
    id: 'item-misir-wot',
    nameEn: 'Misir Wot',
    nameAm: 'ምስር ወጥ',
    descriptionEn: 'Spicy red lentil stew simmered with berbere and onions, a staple of Ethiopian cuisine.',
    descriptionAm: 'በበርበሬ እና ሽንኩርት የተቀቀለ የቀይ ምስር ወጥ።',
    price: 110,
    categoryId: 'cat-appetizers',
    emoji: '🫘',
    imageColor: '#C0392B',
    isVegetarian: true,
    isSpicy: true,
    isAvailable: true,
    modifiers: [
      {
        id: 'mod-misir-spice',
        nameEn: 'Spice Level',
        nameAm: 'ቅመም ደረጃ',
        required: true,
        singleSelect: true,
        options: [
          { id: 'opt-misir-mild', nameEn: 'Mild', nameAm: 'ያልተቀመመ', price: 0 },
          { id: 'opt-misir-medium', nameEn: 'Medium', nameAm: 'መካከለኛ', price: 0 },
          { id: 'opt-misir-hot', nameEn: 'Hot', nameAm: 'መራራ', price: 0 },
        ],
      },
    ],
    addons: [
      { id: 'addon-injera-misir', nameEn: 'Extra Injera', nameAm: 'ተጨማሪ እንጀራ', price: 25 },
    ],
  },

  // Main Course
  {
    id: 'item-doro-wot',
    nameEn: 'Doro Wot',
    nameAm: 'ዶሮ ወጥ',
    descriptionEn: 'The crown jewel of Ethiopian cuisine — slow-cooked chicken stew with berbere, served with a boiled egg and injera.',
    descriptionAm: 'የኢትዮጵያ ምግብ አበጋዛ — በበርበሬ የተረፋ ዶሮ ወጥ ከቦይልድ እንቁላል እና እንጀራ ጋር።',
    price: 280,
    categoryId: 'cat-mains',
    emoji: '🍗',
    imageColor: '#8B4513',
    isVegetarian: false,
    isSpicy: true,
    isAvailable: true,
    modifiers: [
      {
        id: 'mod-doro-spice',
        nameEn: 'Spice Level',
        nameAm: 'ቅመም ደረጃ',
        required: true,
        singleSelect: true,
        options: [
          { id: 'opt-doro-mild', nameEn: 'Mild', nameAm: 'ያልተቀመመ', price: 0 },
          { id: 'opt-doro-medium', nameEn: 'Medium', nameAm: 'መካከለኛ', price: 0 },
          { id: 'opt-doro-hot', nameEn: 'Hot', nameAm: 'መራራ', price: 0 },
        ],
      },
      {
        id: 'mod-doro-pieces',
        nameEn: 'Chicken Pieces',
        nameAm: 'ዶሮ ቁራጭ',
        required: true,
        singleSelect: true,
        options: [
          { id: 'opt-1pc', nameEn: '1 Piece', nameAm: '1 ቁራጭ', price: 0 },
          { id: 'opt-2pc', nameEn: '2 Pieces', nameAm: '2 ቁራጭ', price: 100 },
        ],
      },
    ],
    addons: [
      { id: 'addon-injera-doro', nameEn: 'Extra Injera', nameAm: 'ተጨማሪ እንጀራ', price: 25 },
      { id: 'addon-egg-doro', nameEn: 'Extra Egg', nameAm: 'ተጨማሪ እንቁላል', price: 20 },
      { id: 'addon-ayib-doro', nameEn: 'Ayib (Cottage Cheese)', nameAm: 'አይብ', price: 35 },
    ],
  },
  {
    id: 'item-kitfo',
    nameEn: 'Kitfo',
    nameAm: 'ኪትፎ',
    descriptionEn: 'Finely minced raw beef seasoned with mitmita spice and niter kibbeh, a delicacy of the Gurage people.',
    descriptionAm: 'በሚጥሚጥ ቅመም እና ንጥር ቅቤ የተቀመመ የተፈጨ ስጋ።',
    price: 350,
    categoryId: 'cat-mains',
    emoji: '🥩',
    imageColor: '#922B21',
    isVegetarian: false,
    isSpicy: true,
    isAvailable: true,
    modifiers: [
      {
        id: 'mod-kitfo-cook',
        nameEn: 'Cooking Level',
        nameAm: 'የማብሰያ ደረጃ',
        required: true,
        singleSelect: true,
        options: [
          { id: 'opt-raw', nameEn: 'Raw (Tere)', nameAm: 'ስጋ (ቴሬ)', price: 0 },
          { id: 'opt-leb-leb', nameEn: 'Slightly Cooked (Leb-Leb)', nameAm: 'ትንሽ የተበሰለ (ለብ-ለብ)', price: 0 },
          { id: 'opt-well', nameEn: 'Well Done', nameAm: 'ደምብ የተበሰለ', price: 0 },
        ],
      },
    ],
    addons: [
      { id: 'addon-injera-kitfo', nameEn: 'Extra Injera', nameAm: 'ተጨማሪ እንጀራ', price: 25 },
      { id: 'addon-kocho-kitfo', nameEn: 'Kocho (False Banana Bread)', nameAm: 'ቆጮ', price: 30 },
      { id: 'addon-ayib-kitfo', nameEn: 'Ayib (Cottage Cheese)', nameAm: 'አይብ', price: 35 },
    ],
  },
  {
    id: 'item-tibs',
    nameEn: 'Tibs',
    nameAm: 'ጥብስ',
    descriptionEn: 'Sautéed beef cubes with onions, peppers, and rosemary, sizzling hot and full of flavor.',
    descriptionAm: 'ከሽንኩርት፣ ፍላቹ እና ሮዝማሪ ጋር የተጠበሰ የስጋ ኩቤ።',
    price: 300,
    categoryId: 'cat-mains',
    emoji: '🥘',
    imageColor: '#E67E22',
    isVegetarian: false,
    isSpicy: false,
    isAvailable: true,
    modifiers: [
      {
        id: 'mod-tibs-spice',
        nameEn: 'Spice Level',
        nameAm: 'ቅመም ደረጃ',
        required: true,
        singleSelect: true,
        options: [
          { id: 'opt-tibs-mild', nameEn: 'Mild', nameAm: 'ያልተቀመመ', price: 0 },
          { id: 'opt-tibs-medium', nameEn: 'Medium', nameAm: 'መካከለኛ', price: 0 },
          { id: 'opt-tibs-hot', nameEn: 'Hot (Key Sir)', nameAm: 'መራራ (ቀይ ስር)', price: 0 },
        ],
      },
      {
        id: 'mod-tibs-size',
        nameEn: 'Size',
        nameAm: 'መጠን',
        required: true,
        singleSelect: true,
        options: [
          { id: 'opt-tibs-regular', nameEn: 'Regular', nameAm: 'መደበኛ', price: 0 },
          { id: 'opt-tibs-large', nameEn: 'Large', nameAm: 'ትልቅ', price: 80 },
        ],
      },
    ],
    addons: [
      { id: 'addon-injera-tibs', nameEn: 'Extra Injera', nameAm: 'ተጨማሪ እንጀራ', price: 25 },
      { id: 'addon-awaze-tibs', nameEn: 'Awaze Dip', nameAm: 'አዋዜ መጥመቅ', price: 20 },
    ],
  },
  {
    id: 'item-dulet',
    nameEn: 'Dulet',
    nameAm: 'ዱሌት',
    descriptionEn: 'Spicy tripe, liver, and lean beef mince sautéed with onions, garlic, and chili. A bold and flavorful specialty.',
    descriptionAm: 'ቅመም ያለው የከብት አሳማ ስጋ፣ ጥቁር እና ነጭ ሽንኩርት የተጠበሰ።',
    price: 320,
    categoryId: 'cat-mains',
    emoji: '🔥',
    imageColor: '#B7410E',
    isVegetarian: false,
    isSpicy: true,
    isAvailable: true,
    modifiers: [
      {
        id: 'mod-dulet-spice',
        nameEn: 'Spice Level',
        nameAm: 'ቅመም ደረጃ',
        required: true,
        singleSelect: true,
        options: [
          { id: 'opt-dulet-mild', nameEn: 'Mild', nameAm: 'ያልተቀመመ', price: 0 },
          { id: 'opt-dulet-medium', nameEn: 'Medium', nameAm: 'መካከለኛ', price: 0 },
          { id: 'opt-dulet-hot', nameEn: 'Very Hot', nameAm: 'በጣም መራራ', price: 0 },
        ],
      },
    ],
    addons: [
      { id: 'addon-injera-dulet', nameEn: 'Extra Injera', nameAm: 'ተጨማሪ እንጀራ', price: 25 },
    ],
  },
  {
    id: 'item-firfir',
    nameEn: 'Firfir',
    nameAm: 'ፍርፍር',
    descriptionEn: 'Shredded injera stir-fried with berbere sauce, onions, and niter kibbeh. A popular breakfast and comfort food.',
    descriptionAm: 'በበርበሬ መረቅ፣ ሽንኩርት እና ንጥር ቅቤ የተፈጨ እንጀራ።',
    price: 150,
    categoryId: 'cat-mains',
    emoji: '🍲',
    imageColor: '#CD853F',
    isVegetarian: true,
    isSpicy: true,
    isAvailable: true,
    modifiers: [
      {
        id: 'mod-firfir-spice',
        nameEn: 'Spice Level',
        nameAm: 'ቅመም ደረጃ',
        required: true,
        singleSelect: true,
        options: [
          { id: 'opt-firfir-mild', nameEn: 'Mild', nameAm: 'ያልተቀመመ', price: 0 },
          { id: 'opt-firfir-medium', nameEn: 'Medium', nameAm: 'መካከለኛ', price: 0 },
          { id: 'opt-firfir-hot', nameEn: 'Hot', nameAm: 'መራራ', price: 0 },
        ],
      },
    ],
    addons: [
      { id: 'addon-egg-firfir', nameEn: 'Boiled Egg', nameAm: 'የተቀቀለ እንቁላል', price: 20 },
      { id: 'addon-yogurt-firfir', nameEn: 'Yogurt', nameAm: 'ወተት አይብ', price: 30 },
    ],
  },

  // Drinks
  {
    id: 'item-tej',
    nameEn: 'Tej (Honey Wine)',
    nameAm: 'ጠጀ',
    descriptionEn: 'Traditional Ethiopian honey wine flavored with gesho leaves, served in a berele. Sweet and potent.',
    descriptionAm: 'በጌሾ ቅጠል የተጣፈጠ ባህላዊ የኢትዮጵያ የማር ወይን።',
    price: 80,
    categoryId: 'cat-drinks',
    emoji: '🍷',
    imageColor: '#DAA520',
    isVegetarian: true,
    isSpicy: false,
    isAvailable: true,
    modifiers: [
      {
        id: 'mod-tej-size',
        nameEn: 'Size',
        nameAm: 'መጠን',
        required: true,
        singleSelect: true,
        options: [
          { id: 'opt-tej-glass', nameEn: 'Glass', nameAm: 'ብርጭቆ', price: 0 },
          { id: 'opt-tej-bottle', nameEn: 'Bottle', nameAm: 'ጠርሙስ', price: 200 },
        ],
      },
    ],
    addons: [],
  },
  {
    id: 'item-coffee',
    nameEn: 'Ethiopian Coffee',
    nameAm: 'የኢትዮጵያ ቡና',
    descriptionEn: 'Freshly roasted and brewed Ethiopian coffee, the birthplace of coffee. Served in a traditional Jebena.',
    descriptionAm: 'በባህላዊ ጀበና የተጋገረ የኢትዮጵያ ቡና።',
    price: 50,
    categoryId: 'cat-drinks',
    emoji: '☕',
    imageColor: '#3E2723',
    isVegetarian: true,
    isSpicy: false,
    isAvailable: true,
    modifiers: [
      {
        id: 'mod-coffee-sugar',
        nameEn: 'Sugar',
        nameAm: 'ስኳር',
        required: false,
        singleSelect: true,
        options: [
          { id: 'opt-no-sugar', nameEn: 'No Sugar', nameAm: 'ያለ ስኳር', price: 0 },
          { id: 'opt-little-sugar', nameEn: 'Little Sugar', nameAm: 'ትንሽ ስኳር', price: 0 },
          { id: 'opt-sweet', nameEn: 'Sweet', nameAm: 'ጣፋጭ', price: 0 },
        ],
      },
    ],
    addons: [
      { id: 'addon-snack-coffee', nameEn: 'Snack Popcorn', nameAm: 'ፖፕኮርን', price: 15 },
    ],
  },
  {
    id: 'item-tela',
    nameEn: 'Tella (Local Beer)',
    nameAm: 'ጠላ',
    descriptionEn: 'Traditional Ethiopian home-brewed beer made from teff, barley, and gesho. Refreshing and cultural.',
    descriptionAm: 'ከጤፍ፣ ገብስ እና ጌሾ የሚሰራ ባህላዊ የኢትዮጵያ ቢራ።',
    price: 60,
    categoryId: 'cat-drinks',
    emoji: '🍺',
    imageColor: '#8B6914',
    isVegetarian: true,
    isSpicy: false,
    isAvailable: true,
    modifiers: [],
    addons: [],
  },
  {
    id: 'item-mango-juice',
    nameEn: 'Fresh Mango Juice',
    nameAm: 'ትኩስ የማንጎ ጭማቂ',
    descriptionEn: 'Freshly squeezed mango juice from locally grown Ethiopian mangoes.',
    descriptionAm: 'ከአገር ውስጥ ከተመረተ ማንጎ የተጭመቀ ጭማቂ።',
    price: 45,
    categoryId: 'cat-drinks',
    emoji: '🥭',
    imageColor: '#FF8C00',
    isVegetarian: true,
    isSpicy: false,
    isAvailable: true,
    modifiers: [],
    addons: [],
  },

  // Desserts
  {
    id: 'item-himbasha',
    nameEn: 'Himbasha',
    nameAm: 'ሕምባሻ',
    descriptionEn: 'Sweet Ethiopian bread with cardamom and raisins, beautifully decorated and perfect with coffee.',
    descriptionAm: 'በካርዳሞን እና ዘቢብ የተለበሰ የኢትዮጵያ ጣፋጭ ዳቦ።',
    price: 60,
    categoryId: 'cat-desserts',
    emoji: '🍞',
    imageColor: '#C4A484',
    isVegetarian: true,
    isSpicy: false,
    isAvailable: true,
    modifiers: [],
    addons: [
      { id: 'addon-honey-himbasha', nameEn: 'Honey Drizzle', nameAm: 'የማር ሽበት', price: 15 },
    ],
  },
  {
    id: 'item-kita',
    nameEn: 'Kita with Honey',
    nameAm: 'ቂጣ ከማር',
    descriptionEn: 'Thin flatbread served with wild Ethiopian honey and fresh butter. A simple, sweet indulgence.',
    descriptionAm: 'ከዱር ማር እና ቅቤ ጋር የሚቀርብ ቀጭን ዳቦ።',
    price: 70,
    categoryId: 'cat-desserts',
    emoji: '🍯',
    imageColor: '#E8B828',
    isVegetarian: true,
    isSpicy: false,
    isAvailable: true,
    modifiers: [],
    addons: [],
  },
  {
    id: 'item-ashouka',
    nameEn: 'Ashouka (Fruit Salad)',
    nameAm: 'አሾካ',
    descriptionEn: 'Mixed fresh fruits with honey and yogurt — mango, banana, papaya, and avocado.',
    descriptionAm: 'ከማር እና ወተት አይብ ጋር የተቀላቀለ ትኩስ ፍሬ — ማንጎ፣ ሙዝ፣ ፓፓያ እና አቮካዶ።',
    price: 90,
    categoryId: 'cat-desserts',
    emoji: '🍉',
    imageColor: '#E91E63',
    isVegetarian: true,
    isSpicy: false,
    isAvailable: false,
    modifiers: [],
    addons: [],
  },
]

export const MOCK_RESTAURANT = {
  nameEn: 'Yene Bet',
  nameAm: 'የኔ ቤት',
  taglineEn: 'Authentic Ethiopian Cuisine',
  taglineAm: 'እውነተኛ የኢትዮጵያ ምግብ',
  tableNumber: 7,
  branchNameEn: 'Bole Branch',
  branchNameAm: 'ቦሌ ቅርንጫፍ',
}
