'use client';

// ============================================================
// Yene QR — Reusable Inline Emoji Picker
// ============================================================
// A self-contained emoji picker with:
//   - Search input (filters by keyword)
//   - Category tabs (Food, Drinks, People, Animals, Nature,
//     Activities, Travel, Objects, Symbols, Flags)
//   - Scrollable grid of ~700+ emojis
//   - Recently-used row (persists to localStorage)
//   - Click-to-select with hover preview
//
// Usage:
//   <EmojiPicker value={icon} onChange={setIcon} />
//
// No external dependencies — uses a curated emoji dataset defined
// inline below so it works offline and adds zero bundle weight
// beyond the emojis themselves.
// ============================================================

import { useState, useMemo, useEffect, useRef } from 'react';
import { Search, X } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { cn } from '@/lib/utils';

// ─── Emoji Dataset ──────────────────────────────────────────
// Each entry: { emoji, keywords: string[] } — keywords power the
// search filter (lowercased, includes name + common synonyms).

type EmojiEntry = { e: string; k: string[] };

const FOOD: EmojiEntry[] = [
  { e: '🍕', k: ['pizza', 'slice', 'italian', 'cheese'] },
  { e: '🍔', k: ['burger', 'hamburger', 'beef', 'fast food'] },
  { e: '🍟', k: ['fries', 'chips', 'potato', 'fast food'] },
  { e: '🌭', k: ['hotdog', 'hot dog', 'sausage', 'frankfurt'] },
  { e: '🥪', k: ['sandwich', 'bread', 'lunch'] },
  { e: '🌮', k: ['taco', 'mexican', 'shell'] },
  { e: '🌯', k: ['burrito', 'mexican', 'wrap'] },
  { e: '🥙', k: ['pita', 'wrap', 'kebab', 'shawarma', 'flatbread'] },
  { e: '🧆', k: ['falafel', 'middle eastern', 'chickpea'] },
  { e: '🍳', k: ['egg', 'fried', 'breakfast', 'sunny side'] },
  { e: '🥚', k: ['egg', 'raw', 'boiled'] },
  { e: '🥓', k: ['bacon', 'pork', 'breakfast', 'strip'] },
  { e: '🥞', k: ['pancakes', 'breakfast', 'syrup', 'stack'] },
  { e: '🧇', k: ['waffle', 'breakfast', 'grid'] },
  { e: '🥯', k: ['bagel', 'bread', 'breakfast'] },
  { e: '🍞', k: ['bread', 'loaf', 'slice', 'bake'] },
  { e: '🥐', k: ['croissant', 'french', 'pastry', 'breakfast'] },
  { e: '🥖', k: ['baguette', 'french', 'bread', 'loaf'] },
  { e: '🧀', k: ['cheese', 'wedge', 'dairy'] },
  { e: '🥨', k: ['pretzel', 'snack', 'salt'] },
  { e: '🧄', k: ['garlic', 'bulb', 'spice'] },
  { e: '🧅', k: ['onion', 'bulb', 'root'] },
  { e: '🥔', k: ['potato', 'spud', 'root'] },
  { e: '🍠', k: ['sweet potato', 'yam', 'roasted'] },
  { e: '🥐', k: ['croissant', 'pastry'] },
  { e: '🧁', k: ['cupcake', 'muffin', 'sweet', 'dessert'] },
  { e: '🍰', k: ['cake', 'slice', 'dessert', 'birthday'] },
  { e: '🎂', k: ['birthday', 'cake', 'candle', 'celebration'] },
  { e: '🍪', k: ['cookie', 'biscuit', 'chocolate chip'] },
  { e: '🍩', k: ['donut', 'doughnut', 'sweet', 'glazed'] },
  { e: '🍫', k: ['chocolate', 'bar', 'sweet'] },
  { e: '🍬', k: ['candy', 'sweet', 'sugar'] },
  { e: '🍭', k: ['lollipop', 'sweet', 'candy'] },
  { e: '🍮', k: ['pudding', 'custard', 'dessert', 'flan'] },
  { e: '🍯', k: ['honey', 'pot', 'sweet', 'bee'] },
  { e: '🍼', k: ['baby bottle', 'milk', 'infant'] },
  { e: '🥛', k: ['milk', 'glass', 'dairy', 'drink'] },
  { e: '☕', k: ['coffee', 'cup', 'espresso', 'caffeine', 'hot'] },
  { e: '🍵', k: ['tea', 'green', 'matcha', 'cup', 'hot'] },
  { e: '🧋', k: ['bubble tea', 'boba', 'tapioca', 'milk tea'] },
  { e: '🥤', k: ['soda', 'cup', 'straw', 'drink', 'soft drink'] },
  { e: '🧃', k: ['juice box', 'drink', 'fruit'] },
  { e: '🧉', k: ['mate', 'yerba', 'drink', 'gourd'] },
  { e: '🍺', k: ['beer', 'mug', 'ale', 'alcohol', 'drink'] },
  { e: '🍻', k: ['beers', 'cheers', 'mug', 'alcohol'] },
  { e: '🥃', k: ['whiskey', 'tumbler', 'bourbon', 'alcohol'] },
  { e: '🥂', k: ['cheers', 'clink', 'champagne', 'celebrate'] },
  { e: '🍷', k: ['wine', 'glass', 'red', 'alcohol', 'drink'] },
  { e: '🍸', k: ['martini', 'cocktail', 'alcohol', 'drink'] },
  { e: '🍹', k: ['tropical', 'cocktail', 'drink', 'fruit', 'umbrella'] },
  { e: '🍾', k: ['champagne', 'bottle', 'celebration', 'pop'] },
  { e: '🍶', k: ['sake', 'bottle', 'japanese', 'alcohol'] },
  { e: '🍴', k: ['fork', 'knife', 'cutlery', 'dining', 'utensils'] },
  { e: '🍽️', k: ['plate', 'fork', 'knife', 'dining', 'meal'] },
  { e: '🥄', k: ['spoon', 'utensil', 'soup'] },
  { e: '🥢', k: ['chopsticks', 'asian', 'utensil'] },
  { e: '🧂', k: ['salt', 'shaker', 'seasoning'] },
  { e: '🍲', k: ['pot', 'stew', 'soup', 'meal', 'broth'] },
  { e: '🍛', k: ['curry', 'rice', 'indian', 'japanese', 'spicy'] },
  { e: '🍜', k: ['noodle', 'ramen', 'soup', 'bowl', 'japanese'] },
  { e: '🍝', k: ['spaghetti', 'pasta', 'noodle', 'italian'] },
  { e: '🍱', k: ['bento', 'box', 'lunch', 'japanese'] },
  { e: '🥘', k: ['paella', 'pan', 'shallow', 'meal', 'seafood'] },
  { e: '🥩', k: ['steak', 'meat', 'beef', 'cut'] },
  { e: '🍖', k: ['meat', 'bone', 'pork', 'mutton', 'chop'] },
  { e: '🍗', k: ['chicken', 'leg', 'drumstick', 'poultry'] },
  { e: '🐟', k: ['fish', 'animal', 'seafood', 'fresh'] },
  { e: '🐠', k: ['fish', 'tropical', 'aquarium', 'seafood'] },
  { e: '🐡', k: ['puffer', 'fish', 'blowfish', 'seafood'] },
  { e: '🦐', k: ['shrimp', 'prawn', 'seafood', 'shellfish'] },
  { e: '🦞', k: ['lobster', 'seafood', 'shellfish', 'crustacean'] },
  { e: '🦀', k: ['crab', 'seafood', 'shellfish', 'crustacean'] },
  { e: '🐙', k: ['octopus', 'seafood', 'tentacle', 'animal'] },
  { e: '🦑', k: ['squid', 'seafood', 'tentacle', 'calamari'] },
  { e: '🍤', k: ['fried shrimp', 'tempura', 'prawn', 'seafood'] },
  { e: '🥗', k: ['salad', 'greens', 'healthy', 'bowl', 'vegetable'] },
  { e: '🫓', k: ['flatbread', 'injera', 'naan', 'pita'] },
  { e: '🧆', k: ['falafel', 'middle eastern'] },
  { e: '🌶️', k: ['chili', 'pepper', 'hot', 'spicy'] },
  { e: '🫑', k: ['bell pepper', 'capsicum', 'vegetable'] },
  { e: '🥦', k: ['broccoli', 'vegetable', 'green'] },
  { e: '🥬', k: ['lettuce', 'leafy', 'green', 'salad', 'vegetable'] },
  { e: '🥒', k: ['cucumber', 'pickle', 'vegetable', 'green'] },
  { e: '🌽', k: ['corn', 'maize', 'cob', 'yellow', 'vegetable'] },
  { e: '🥕', k: ['carrot', 'vegetable', 'root', 'orange'] },
  { e: '🫛', k: ['pea', 'pod', 'green', 'vegetable'] },
  { e: '🫒', k: ['olive', 'green', 'mediterranean'] },
  { e: '🧅', k: ['onion', 'bulb'] },
  { e: '🍄', k: ['mushroom', 'fungi', 'vegetable'] },
  { e: '🥑', k: ['avocado', 'fruit', 'green', 'guac'] },
  { e: '🍅', k: ['tomato', 'fruit', 'red', 'sauce'] },
  { e: '🍆', k: ['eggplant', 'aubergine', 'vegetable', 'purple'] },
  { e: '🥝', k: ['kiwi', 'fruit', 'green', 'new zealand'] },
  { e: '🍍', k: ['pineapple', 'fruit', 'tropical', 'yellow'] },
  { e: '🥥', k: ['coconut', 'fruit', 'tropical', 'brown'] },
  { e: '🥭', k: ['mango', 'fruit', 'tropical', 'yellow', 'orange'] },
  { e: '🍑', k: ['peach', 'fruit', 'pink', 'stone'] },
  { e: '🍒', k: ['cherry', 'fruit', 'red', 'stem'] },
  { e: '🍓', k: ['strawberry', 'fruit', 'red', 'berry'] },
  { e: '🫐', k: ['blueberry', 'berry', 'fruit', 'blue'] },
  { e: '🍈', k: ['melon', 'fruit', 'cantaloupe', 'yellow'] },
  { e: '🍉', k: ['watermelon', 'fruit', 'red', 'summer'] },
  { e: '🍇', k: ['grape', 'fruit', 'wine', 'purple', 'green'] },
  { e: '🍊', k: ['orange', 'fruit', 'citrus', 'tangerine'] },
  { e: '🍋', k: ['lemon', 'fruit', 'citrus', 'yellow', 'sour'] },
  { e: '🍋‍🟩', k: ['lime', 'citrus', 'green', 'sour'] },
  { e: '🍎', k: ['apple', 'fruit', 'red', 'teacher'] },
  { e: '🍏', k: ['apple', 'green', 'fruit', 'granny smith'] },
  { e: '🍐', k: ['pear', 'fruit', 'green', 'yellow'] },
  { e: '🍌', k: ['banana', 'fruit', 'yellow', 'monkey'] },
  { e: '🔥', k: ['fire', 'hot', 'flame', 'spicy', 'grill'] },
  { e: '⭐', k: ['star', 'favorite', 'featured', 'popular'] },
  { e: '👑', k: ['crown', 'king', 'queen', 'royal', 'vip'] },
  { e: '💎', k: ['diamond', 'gem', 'jewel', 'premium', 'vip'] },
];

const DRINKS: EmojiEntry[] = [
  { e: '☕', k: ['coffee', 'espresso', 'caffeine', 'hot'] },
  { e: '🍵', k: ['tea', 'green', 'matcha', 'herbal', 'hot'] },
  { e: '🧋', k: ['bubble tea', 'boba', 'milk tea', 'tapioca'] },
  { e: '🥤', k: ['soda', 'soft drink', 'cup', 'straw', 'cola'] },
  { e: '🧃', k: ['juice', 'box', 'fruit', 'drink'] },
  { e: '🥛', k: ['milk', 'glass', 'dairy', 'white'] },
  { e: '🍺', k: ['beer', 'mug', 'ale', 'lager', 'alcohol'] },
  { e: '🍻', k: ['beer', 'cheers', 'mug', 'alcohol', 'party'] },
  { e: '🥃', k: ['whiskey', 'bourbon', 'scotch', 'tumbler'] },
  { e: '🥂', k: ['cheers', 'champagne', 'celebrate', 'toast'] },
  { e: '🍷', k: ['wine', 'red', 'glass', 'alcohol'] },
  { e: '🍸', k: ['martini', 'cocktail', 'alcohol'] },
  { e: '🍹', k: ['tropical', 'cocktail', 'fruit', 'umbrella'] },
  { e: '🍾', k: ['champagne', 'bottle', 'celebrate', 'new year'] },
  { e: '🍶', k: ['sake', 'japanese', 'alcohol', 'bottle'] },
  { e: '🧉', k: ['mate', 'yerba', 'gourd', 'drink'] },
  { e: '🥄', k: ['spoon', 'stir'] },
  { e: '🧊', k: ['ice', 'cube', 'cold', 'frozen'] },
  { e: '🫖', k: ['teapot', 'tea', 'kettle', 'hot'] },
  { e: '☕', k: ['coffee'] },
  { e: '🍵', k: ['tea'] },
  { e: '🧋', k: ['boba'] },
  { e: '🥤', k: ['soda'] },
  { e: '🧃', k: ['juice'] },
  { e: '🥛', k: ['milk'] },
  { e: '🍺', k: ['beer'] },
  { e: '🍷', k: ['wine'] },
  { e: '🍸', k: ['martini'] },
  { e: '🍹', k: ['cocktail'] },
  { e: '🍾', k: ['champagne'] },
  { e: '🥃', k: ['whiskey'] },
  { e: '🧊', k: ['ice'] },
  { e: '🫖', k: ['teapot'] },
];

const PEOPLE: EmojiEntry[] = [
  { e: '👤', k: ['person', 'user', 'profile', 'silhouette'] },
  { e: '👥', k: ['people', 'group', 'users', 'crowd'] },
  { e: '🧑', k: ['person', 'adult', 'human'] },
  { e: '👨', k: ['man', 'male', 'person'] },
  { e: '👩', k: ['woman', 'female', 'person'] },
  { e: '🧓', k: ['older person', 'elder', 'senior'] },
  { e: '👴', k: ['old man', 'grandfather', 'elder'] },
  { e: '👵', k: ['old woman', 'grandmother', 'elder'] },
  { e: '🧔', k: ['bearded person', 'man', 'facial hair'] },
  { e: '👨‍🦰', k: ['man', 'red hair', 'ginger'] },
  { e: '👩‍🦰', k: ['woman', 'red hair', 'ginger'] },
  { e: '👨‍🦱', k: ['man', 'curly hair'] },
  { e: '👩‍🦱', k: ['woman', 'curly hair'] },
  { e: '👨‍🦳', k: ['man', 'white hair', 'gray'] },
  { e: '👩‍🦳', k: ['woman', 'white hair', 'gray'] },
  { e: '👨‍🦲', k: ['man', 'bald'] },
  { e: '👩‍🦲', k: ['woman', 'bald'] },
  { e: '👶', k: ['baby', 'infant', 'child'] },
  { e: '🧒', k: ['child', 'kid'] },
  { e: '👦', k: ['boy', 'child', 'male'] },
  { e: '👧', k: ['girl', 'child', 'female'] },
  { e: '🧑‍🍳', k: ['cook', 'chef', 'kitchen', 'cooking'] },
  { e: '👨‍🍳', k: ['chef', 'cook', 'man', 'kitchen'] },
  { e: '👩‍🍳', k: ['chef', 'cook', 'woman', 'kitchen'] },
  { e: '🧑‍🌾', k: ['farmer', 'farm', 'agriculture'] },
  { e: '🧑‍🔧', k: ['mechanic', 'wrench', 'repair'] },
  { e: '🧑‍💼', k: ['office worker', 'business', 'suit'] },
  { e: '🕵️', k: ['detective', 'spy', 'investigator'] },
  { e: '💂', k: ['guard', 'royal', 'soldier'] },
  { e: '👷', k: ['construction', 'worker', 'hard hat'] },
  { e: '🤴', k: ['prince', 'royal', 'crown'] },
  { e: '👸', k: ['princess', 'royal', 'crown'] },
  { e: '🤵', k: ['tuxedo', 'groom', 'wedding', 'formal'] },
  { e: '👰', k: ['bride', 'veil', 'wedding', 'formal'] },
  { e: '🤰', k: ['pregnant', 'baby', 'expecting'] },
  { e: '🤱', k: ['breastfeeding', 'nursing', 'baby'] },
  { e: '👼', k: ['angel', 'baby', 'wings', 'halo'] },
  { e: '🎅', k: ['santa', 'christmas', 'father christmas'] },
  { e: '🤶', k: ['mrs claus', 'christmas', 'mother christmas'] },
  { e: '🦸', k: ['superhero', 'cape', 'hero'] },
  { e: '🦹', k: ['supervillain', 'villain', 'cape'] },
  { e: '🧙', k: ['wizard', 'mage', 'magic', 'witch'] },
  { e: '🧚', k: ['fairy', 'magic', 'wings'] },
  { e: '🧛', k: ['vampire', 'dracula', 'fang'] },
  { e: '🧜', k: ['mermaid', 'merperson', 'sea'] },
  { e: '🧝', k: ['elf', 'pointed ears', 'fantasy'] },
  { e: '🧞', k: ['genie', 'djinn', 'magic'] },
  { e: '🧟', k: ['zombie', 'undead', 'walking dead'] },
  { e: '💆', k: ['massage', 'spa', 'relax', 'face'] },
  { e: '💇', k: ['haircut', 'salon', 'barber'] },
  { e: '🚶', k: ['walking', 'person', 'pedestrian'] },
  { e: '🏃', k: ['running', 'runner', 'jog', 'sprint'] },
  { e: '💃', k: ['dancing', 'woman', 'dance'] },
  { e: '🕺', k: ['dancing', 'man', 'dance'] },
  { e: '👯', k: ['dancers', 'bunny ears', 'party'] },
  { e: '🧘', k: ['meditation', 'yoga', 'lotus', 'zen'] },
  { e: '🛀', k: ['bath', 'bathtub', 'relax', 'spa'] },
  { e: '🛌', k: ['sleep', 'bed', 'rest', 'night'] },
  { e: '🤷', k: ['shrug', 'whatever', 'idk'] },
  { e: '🤦', k: ['facepalm', 'omg', 'frustrated'] },
  { e: '🤝', k: ['handshake', 'deal', 'agreement'] },
  { e: '🙏', k: ['pray', 'please', 'thanks', 'namaste'] },
  { e: '👍', k: ['thumbs up', 'like', 'yes', 'good'] },
  { e: '👎', k: ['thumbs down', 'dislike', 'no', 'bad'] },
  { e: '👌', k: ['ok', 'okay', 'perfect', 'good'] },
  { e: '✌️', k: ['peace', 'victory', 'two fingers'] },
  { e: '🤞', k: ['fingers crossed', 'hope', 'luck'] },
  { e: '🤟', k: ['love you', 'rock on', 'horns'] },
  { e: '🤙', k: ['call me', 'shaka', 'hang loose'] },
  { e: '👈', k: ['point left', 'back', 'previous'] },
  { e: '👉', k: ['point right', 'forward', 'next'] },
  { e: '👆', k: ['point up', 'above', 'click'] },
  { e: '👇', k: ['point down', 'below', 'here'] },
  { e: '☝️', k: ['one', 'point up', 'number one'] },
  { e: '✋', k: ['stop', 'raised hand', 'high five'] },
  { e: '👋', k: ['wave', 'hello', 'hi', 'bye'] },
  { e: '🤚', k: ['stop', 'raised back', 'palm'] },
  { e: '🖐️', k: ['hand', 'five', 'fingers'] },
  { e: '🖖', k: ['vulcan', 'spock', 'star trek', 'live long'] },
  { e: '👏', k: ['clap', 'applause', 'cheer'] },
  { e: '🙌', k: ['raise hands', 'celebrate', 'praise'] },
  { e: '🤲', k: ['palms up', 'open', 'receive'] },
  { e: '🤜', k: ['fist bump', 'right', 'punch'] },
  { e: '🤛', k: ['fist bump', 'left', 'punch'] },
  { e: '✊', k: ['fist', 'power', 'resist'] },
  { e: '👊', k: ['punch', 'fist', 'fight'] },
  { e: '🤝', k: ['handshake'] },
  { e: '💪', k: ['muscle', 'strong', 'flex', 'workout'] },
  { e: '🫶', k: ['heart hands', 'love'] },
  { e: '❤️', k: ['heart', 'love', 'red', 'romance'] },
  { e: '🧡', k: ['heart', 'orange', 'love'] },
  { e: '💛', k: ['heart', 'yellow', 'love'] },
  { e: '💚', k: ['heart', 'green', 'love'] },
  { e: '💙', k: ['heart', 'blue', 'love'] },
  { e: '💜', k: ['heart', 'purple', 'love'] },
  { e: '🖤', k: ['heart', 'black', 'love'] },
  { e: '🤍', k: ['heart', 'white', 'love'] },
  { e: '🤎', k: ['heart', 'brown', 'love'] },
  { e: '💔', k: ['broken heart', 'sad', 'love lost'] },
  { e: '❣️', k: ['heart exclamation', 'love', 'excited'] },
  { e: '💕', k: ['two hearts', 'love', 'affection'] },
  { e: '💞', k: ['revolving hearts', 'love', 'forever'] },
  { e: '💓', k: ['beating heart', 'love', 'pulse'] },
  { e: '💗', k: ['growing heart', 'love', 'excited'] },
  { e: '💖', k: ['sparkling heart', 'love', 'shiny'] },
  { e: '💘', k: ['cupid', 'heart arrow', 'love'] },
  { e: '💝', k: ['gift heart', 'present', 'love'] },
  { e: '💟', k: ['heart decoration', 'love'] },
];

const ANIMALS: EmojiEntry[] = [
  { e: '🐶', k: ['dog', 'puppy', 'pet', 'pup'] },
  { e: '🐱', k: ['cat', 'kitten', 'pet', 'feline'] },
  { e: '🐭', k: ['mouse', 'rodent', 'rat'] },
  { e: '🐹', k: ['hamster', 'rodent', 'pet'] },
  { e: '🐰', k: ['rabbit', 'bunny', 'hare', 'pet'] },
  { e: '🦊', k: ['fox', 'animal'] },
  { e: '🐻', k: ['bear', 'animal', 'teddy'] },
  { e: '🐼', k: ['panda', 'animal', 'bamboo'] },
  { e: '🐨', k: ['koala', 'animal', 'australia'] },
  { e: '🐯', k: ['tiger', 'animal', 'big cat'] },
  { e: '🦁', k: ['lion', 'animal', 'king', 'big cat'] },
  { e: '🐮', k: ['cow', 'cattle', 'farm', 'moo'] },
  { e: '🐷', k: ['pig', 'hog', 'farm', 'oink'] },
  { e: '🐸', k: ['frog', 'amphibian', 'green'] },
  { e: '🐵', k: ['monkey', 'ape', 'animal'] },
  { e: '🙈', k: ['see no evil', 'monkey', 'eyes'] },
  { e: '🙉', k: ['hear no evil', 'monkey', 'ears'] },
  { e: '🙊', k: ['speak no evil', 'monkey', 'mouth'] },
  { e: '🐒', k: ['monkey', 'animal', 'ape'] },
  { e: '🐔', k: ['chicken', 'hen', 'poultry', 'farm'] },
  { e: '🐧', k: ['penguin', 'bird', 'cold', 'antarctica'] },
  { e: '🐦', k: ['bird', 'tweet', 'animal'] },
  { e: '🐤', k: ['baby chick', 'chicken', 'yellow'] },
  { e: '🦆', k: ['duck', 'bird', 'water'] },
  { e: '🦅', k: ['eagle', 'bird', 'prey'] },
  { e: '🦉', k: ['owl', 'bird', 'night', 'wise'] },
  { e: '🦇', k: ['bat', 'animal', 'vampire', 'night'] },
  { e: '🐺', k: ['wolf', 'animal', 'howl'] },
  { e: '🐗', k: ['boar', 'pig', 'wild'] },
  { e: '🐴', k: ['horse', 'animal', 'stallion'] },
  { e: '🦄', k: ['unicorn', 'horse', 'magic', 'horn'] },
  { e: '🐝', k: ['bee', 'honey', 'insect', 'buzz'] },
  { e: '🐛', k: ['bug', 'caterpillar', 'insect'] },
  { e: '🦋', k: ['butterfly', 'insect', 'wings'] },
  { e: '🐌', k: ['snail', 'slow', 'shell'] },
  { e: '🐞', k: ['ladybug', 'beetle', 'insect'] },
  { e: '🐜', k: ['ant', 'insect', 'worker'] },
  { e: '🦗', k: ['cricket', 'insect', 'chirp'] },
  { e: '🕷️', k: ['spider', 'arachnid', 'web'] },
  { e: '🦂', k: ['scorpion', 'arachnid', 'sting'] },
  { e: '🐢', k: ['turtle', 'tortoise', 'shell', 'slow'] },
  { e: '🐍', k: ['snake', 'serpent', 'python'] },
  { e: '🦎', k: ['lizard', 'reptile', 'gecko'] },
  { e: '🦖', k: ['t-rex', 'dinosaur', 'rex'] },
  { e: '🦕', k: ['dinosaur', 'sauropod', 'brontosaurus'] },
  { e: '🐙', k: ['octopus', 'sea', 'tentacle'] },
  { e: '🦑', k: ['squid', 'sea', 'tentacle'] },
  { e: '🦐', k: ['shrimp', 'prawn', 'sea'] },
  { e: '🦞', k: ['lobster', 'sea', 'shellfish'] },
  { e: '🦀', k: ['crab', 'sea', 'shellfish'] },
  { e: '🐡', k: ['pufferfish', 'fish', 'sea'] },
  { e: '🐠', k: ['fish', 'tropical', 'sea'] },
  { e: '🐟', k: ['fish', 'sea', 'animal'] },
  { e: '🐬', k: ['dolphin', 'sea', 'mammal'] },
  { e: '🐳', k: ['whale', 'sea', 'spout'] },
  { e: '🐋', k: ['whale', 'sea', 'mammal'] },
  { e: '🦈', k: ['shark', 'sea', 'predator'] },
  { e: '🐊', k: ['crocodile', 'alligator', 'reptile'] },
  { e: '🐅', k: ['tiger', 'animal', 'big cat'] },
  { e: '🐆', k: ['leopard', 'animal', 'big cat', 'spots'] },
  { e: '🦓', k: ['zebra', 'animal', 'stripes'] },
  { e: '🦍', k: ['gorilla', 'ape', 'animal'] },
  { e: '🦧', k: ['orangutan', 'ape', 'animal'] },
  { e: '🐘', k: ['elephant', 'animal', 'tusk'] },
  { e: '🦛', k: ['hippo', 'hippopotamus', 'animal'] },
  { e: '🦏', k: ['rhino', 'rhinoceros', 'animal', 'horn'] },
  { e: '🐪', k: ['camel', 'animal', 'desert', 'dromedary'] },
  { e: '🐫', k: ['camel', 'animal', 'desert', 'bactrian'] },
  { e: '🦒', k: ['giraffe', 'animal', 'tall', 'neck'] },
  { e: '🦘', k: ['kangaroo', 'animal', 'australia', 'pouch'] },
  { e: '🐃', k: ['water buffalo', 'ox', 'cow'] },
  { e: '🐂', k: ['ox', 'bull', 'cow', 'cattle'] },
  { e: '🐄', k: ['cow', 'cattle', 'farm'] },
  { e: '🐎', k: ['horse', 'animal', 'gallop'] },
  { e: '🐖', k: ['pig', 'hog', 'farm'] },
  { e: '🐏', k: ['ram', 'sheep', 'horn'] },
  { e: '🐑', k: ['sheep', 'ewe', 'wool', 'farm'] },
  { e: '🐐', k: ['goat', 'animal', 'farm'] },
  { e: '🦙', k: ['llama', 'alpaca', 'animal'] },
  { e: '🐕', k: ['dog', 'puppy', 'pet'] },
  { e: '🐩', k: ['poodle', 'dog', 'groomed'] },
  { e: '🦮', k: ['guide dog', 'service', 'blind'] },
  { e: '🐕‍🦺', k: ['service dog', 'working', 'vest'] },
  { e: '🐈', k: ['cat', 'kitten', 'pet'] },
  { e: '🐓', k: ['rooster', 'chicken', 'cock'] },
  { e: '🦃', k: ['turkey', 'bird', 'thanksgiving'] },
  { e: '🦚', k: ['peacock', 'bird', 'feathers'] },
  { e: '🦜', k: ['parrot', 'bird', 'tropical'] },
  { e: '🦢', k: ['swan', 'bird', 'white'] },
  { e: '🦩', k: ['flamingo', 'bird', 'pink'] },
  { e: '🕊️', k: ['dove', 'bird', 'peace', 'white'] },
  { e: '🐇', k: ['rabbit', 'bunny', 'hare'] },
  { e: '🦝', k: ['raccoon', 'trash panda', 'bandit'] },
  { e: '🦨', k: ['skunk', 'stink', 'striped'] },
  { e: '🦡', k: ['badger', 'animal', 'honey'] },
  { e: '🦦', k: ['otter', 'animal', 'water', 'cute'] },
  { e: '🦥', k: ['sloth', 'slow', 'lazy', 'animal'] },
  { e: '🐁', k: ['mouse', 'rodent', 'small'] },
  { e: '🐀', k: ['rat', 'rodent'] },
  { e: ' CHIP', k: ['chipmunk', 'rodent', 'squirrel'] },
];

const NATURE: EmojiEntry[] = [
  { e: '🌸', k: ['cherry blossom', 'flower', 'pink', 'spring', 'blossom'] },
  { e: '💮', k: ['white flower', 'blossom', 'japanese'] },
  { e: '🏵️', k: ['rosette', 'flower', 'award'] },
  { e: '🌹', k: ['rose', 'flower', 'love', 'red'] },
  { e: '🥀', k: ['wilted flower', 'rose', 'dead'] },
  { e: '🌺', k: ['hibiscus', 'flower', 'tropical'] },
  { e: '🌻', k: ['sunflower', 'flower', 'yellow', 'sun'] },
  { e: '🌼', k: ['blossom', 'flower', 'yellow'] },
  { e: '🌷', k: ['tulip', 'flower', 'spring'] },
  { e: '🌱', k: ['seedling', 'sprout', 'plant', 'green', 'new'] },
  { e: '🌲', k: ['evergreen', 'tree', 'pine', 'forest'] },
  { e: '🌳', k: ['deciduous', 'tree', 'forest'] },
  { e: '🌴', k: ['palm', 'tree', 'tropical', 'beach'] },
  { e: '🌵', k: ['cactus', 'plant', 'desert', 'spike'] },
  { e: '🌾', k: ['sheaf', 'wheat', 'grain', 'harvest'] },
  { e: '🌿', k: ['herb', 'plant', 'green', 'leaf'] },
  { e: '☘️', k: ['shamrock', 'clover', 'green', 'irish'] },
  { e: '🍀', k: ['clover', 'luck', 'green', 'four leaf'] },
  { e: '🍁', k: ['maple leaf', 'leaf', 'fall', 'autumn', 'red', 'canada'] },
  { e: '🍂', k: ['fallen leaf', 'leaf', 'autumn', 'fall'] },
  { e: '🍃', k: ['leaf', 'wind', 'green', 'flutter'] },
  { e: '🍄', k: ['mushroom', 'fungi', 'toadstool'] },
  { e: '🌊', k: ['wave', 'water', 'ocean', 'sea', 'surf'] },
  { e: '💨', k: ['wind', 'blow', 'air', 'fast'] },
  { e: '💧', k: ['droplet', 'water', 'drop', 'sweat'] },
  { e: '💦', k: ['sweat', 'water', 'splash', 'drops'] },
  { e: '☘️', k: ['shamrock'] },
  { e: '🔥', k: ['fire', 'flame', 'hot', 'burn'] },
  { e: '✨', k: ['sparkles', 'shine', 'magic', 'clean'] },
  { e: '⭐', k: ['star', 'yellow', 'night'] },
  { e: '🌟', k: ['glowing star', 'star', 'shine'] },
  { e: '💫', k: ['dizzy', 'star', 'spinning'] },
  { e: '⚡', k: ['lightning', 'zap', 'bolt', 'electric', 'fast'] },
  { e: '☄️', k: ['comet', 'space', 'meteor'] },
  { e: '💥', k: ['explosion', 'boom', 'bang', 'collision'] },
  { e: '🌪️', k: ['tornado', 'twister', 'storm', 'wind'] },
  { e: '🌈', k: ['rainbow', 'color', 'pride', 'sky'] },
  { e: '☀️', k: ['sun', 'sunny', 'weather', 'bright'] },
  { e: '🌤️', k: ['sun behind cloud', 'weather', 'partly cloudy'] },
  { e: '⛅', k: ['sun behind cloud', 'weather', 'partly cloudy'] },
  { e: '🌥️', k: ['cloud', 'weather', 'gray'] },
  { e: '☁️', k: ['cloud', 'weather', 'sky'] },
  { e: '🌦️', k: ['rain', 'sun', 'weather', 'shower'] },
  { e: '🌧️', k: ['rain', 'cloud', 'weather', 'shower'] },
  { e: '⛈️', k: ['thunderstorm', 'rain', 'lightning', 'weather'] },
  { e: '🌩️', k: ['lightning', 'cloud', 'storm', 'weather'] },
  { e: '❄️', k: ['snowflake', 'cold', 'winter', 'frozen'] },
  { e: '🌨️', k: ['snow', 'cloud', 'cold', 'weather'] },
  { e: '⛄', k: ['snowman', 'snow', 'winter', 'cold'] },
  { e: '☃️', k: ['snowman', 'snow', 'winter'] },
  { e: '🌬️', k: ['wind', 'blow', 'weather', 'face'] },
  { e: '🌀', k: ['cyclone', 'hurricane', 'spiral', 'typhoon'] },
  { e: '🌫️', k: ['fog', 'foggy', 'weather', 'mist'] },
  { e: '🌙', k: ['moon', 'crescent', 'night', 'sleep'] },
  { e: '🌚', k: ['moon', 'face', 'new moon', 'night'] },
  { e: '🌝', k: ['moon', 'face', 'full', 'night'] },
  { e: '🌛', k: ['moon', 'first quarter', 'face'] },
  { e: '🌜', k: ['moon', 'last quarter', 'face'] },
  { e: '🌕', k: ['full moon', 'moon', 'night'] },
  { e: '🌖', k: ['waning gibbous', 'moon', 'night'] },
  { e: '🌗', k: ['last quarter', 'moon', 'night'] },
  { e: '🌘', k: ['waning crescent', 'moon', 'night'] },
  { e: '🌑', k: ['new moon', 'moon', 'dark', 'night'] },
  { e: '🌒', k: ['waxing crescent', 'moon', 'night'] },
  { e: '🌓', k: ['first quarter', 'moon', 'night'] },
  { e: '🌔', k: ['waxing gibbous', 'moon', 'night'] },
  { e: '🌍', k: ['earth', 'globe', 'africa', 'europe', 'world'] },
  { e: '🌎', k: ['earth', 'globe', 'americas', 'world'] },
  { e: '🌏', k: ['earth', 'globe', 'asia', 'australia', 'world'] },
  { e: '🪐', k: ['planet', 'saturn', 'ring', 'space'] },
  { e: '💫', k: ['dizzy', 'star'] },
  { e: '⭐', k: ['star'] },
  { e: '🌟', k: ['star', 'glow'] },
  { e: '✨', k: ['sparkle', 'shine'] },
  { e: '⚡', k: ['lightning', 'energy'] },
  { e: '🔥', k: ['fire', 'hot'] },
  { e: '💥', k: ['explosion'] },
  { e: '🌋', k: ['volcano', 'eruption', 'lava'] },
  { e: '🏔️', k: ['mountain', 'snow', 'peak'] },
  { e: '⛰️', k: ['mountain', 'peak', 'rock'] },
  { e: '🗻', k: ['mount fuji', 'mountain', 'snow', 'japan'] },
  { e: '🏕️', k: ['camping', 'tent', 'outdoors'] },
  { e: '🏖️', k: ['beach', 'umbrella', 'sand', 'summer'] },
  { e: '🏜️', k: ['desert', 'sand', 'dry'] },
  { e: '🏝️', k: ['island', 'palm', 'desert', 'tropical'] },
  { e: '🏞️', k: ['national park', 'nature', 'river', 'mountain'] },
];

const ACTIVITIES: EmojiEntry[] = [
  { e: '⚽', k: ['soccer', 'football', 'ball', 'sport'] },
  { e: '🏀', k: ['basketball', 'ball', 'sport', 'hoop'] },
  { e: '🏈', k: ['football', 'american', 'ball', 'sport'] },
  { e: '⚾', k: ['baseball', 'ball', 'sport'] },
  { e: '🥎', k: ['softball', 'ball', 'sport'] },
  { e: '🎾', k: ['tennis', 'ball', 'sport', 'racket'] },
  { e: '🏐', k: ['volleyball', 'ball', 'sport'] },
  { e: '🏉', k: ['rugby', 'football', 'ball', 'sport'] },
  { e: '🥏', k: ['frisbee', 'flying disc', 'sport'] },
  { e: '🎱', k: ['pool', 'billiards', '8 ball', 'sport'] },
  { e: '🏓', k: ['ping pong', 'table tennis', 'paddle', 'sport'] },
  { e: '🏸', k: ['badminton', 'racket', 'shuttlecock', 'sport'] },
  { e: '🥅', k: ['goal', 'net', 'soccer', 'hockey'] },
  { e: '🏒', k: ['hockey', 'ice', 'puck', 'sport'] },
  { e: '🏑', k: ['hockey', 'field', 'stick', 'sport'] },
  { e: '🥍', k: ['lacrosse', 'stick', 'sport'] },
  { e: '🏏', k: ['cricket', 'bat', 'ball', 'sport'] },
  { e: '⛳', k: ['golf', 'flag', 'hole', 'sport'] },
  { e: '🏹', k: ['bow', 'arrow', 'archery', 'sport'] },
  { e: '🎣', k: ['fishing', 'pole', 'fish', 'sport'] },
  { e: '🥊', k: ['boxing', 'glove', 'sport', 'fight'] },
  { e: '🥋', k: ['martial arts', 'gi', 'judo', 'karate'] },
  { e: '🎽', k: ['running shirt', 'jersey', 'sport'] },
  { e: '⛸️', k: ['ice skate', 'skating', 'winter'] },
  { e: '🥌', k: ['curling', 'stone', 'sport', 'winter'] },
  { e: '🛷', k: ['sled', 'sleigh', 'winter', 'snow'] },
  { e: '🎿', k: ['ski', 'skiing', 'winter', 'snow'] },
  { e: '⛷️', k: ['skier', 'ski', 'winter', 'snow'] },
  { e: '🏂', k: ['snowboarder', 'snowboard', 'winter'] },
  { e: '🪂', k: ['parachute', 'parasail', 'sky'] },
  { e: '🏋️', k: ['weight lifter', 'gym', 'workout', 'lift'] },
  { e: '🤼', k: ['wrestling', 'wrestlers', 'sport'] },
  { e: '🤸', k: ['cartwheel', 'gymnastics', 'sport'] },
  { e: '⛹️', k: ['basketball', 'bouncing', 'sport'] },
  { e: '🤺', k: ['fencing', 'sword', 'sport'] },
  { e: '🤾', k: ['handball', 'sport'] },
  { e: '🏌️', k: ['golf', 'golfer', 'sport'] },
  { e: '🏇', k: ['horse racing', 'jockey', 'sport'] },
  { e: '🧘', k: ['meditation', 'yoga', 'zen', 'lotus'] },
  { e: '🛀', k: ['bath', 'spa', 'relax'] },
  { e: '🏄', k: ['surfing', 'surfer', 'wave', 'sport'] },
  { e: '🏊', k: ['swimming', 'swimmer', 'water', 'sport'] },
  { e: '🤽', k: ['water polo', 'swim', 'sport'] },
  { e: '🚣', k: ['rowing', 'boat', 'oar', 'water'] },
  { e: '🧗', k: ['climbing', 'rock', 'sport'] },
  { e: '🚵', k: ['mountain biking', 'bike', 'sport'] },
  { e: '🚴', k: ['biking', 'bicycle', 'cycling', 'sport'] },
  { e: '🏆', k: ['trophy', 'award', 'win', 'champion'] },
  { e: '🥇', k: ['gold', 'medal', 'first', 'winner'] },
  { e: '🥈', k: ['silver', 'medal', 'second'] },
  { e: '🥉', k: ['bronze', 'medal', 'third'] },
  { e: '🏅', k: ['medal', 'sport', 'award'] },
  { e: '🎖️', k: ['military medal', 'award'] },
  { e: '🎗️', k: ['ribbon', 'awareness', 'support'] },
  { e: '🎫', k: ['ticket', 'admission', 'event'] },
  { e: '🎟️', k: ['admission tickets', 'event', 'concert'] },
  { e: '🎪', k: ['circus', 'tent', 'show'] },
  { e: '🎭', k: ['theater', 'drama', 'mask', 'arts'] },
  { e: '🎨', k: ['art', 'palette', 'paint', 'color'] },
  { e: '🎬', k: ['movie', 'film', 'clapper', 'cinema'] },
  { e: '🎤', k: ['microphone', 'karaoke', 'sing', 'mic'] },
  { e: '🎧', k: ['headphone', 'music', 'audio', 'listen'] },
  { e: '🎼', k: ['music', 'score', 'notes', 'sheet'] },
  { e: '🎵', k: ['music', 'note', 'single'] },
  { e: '🎶', k: ['music', 'notes', 'multiple'] },
  { e: '🎹', k: ['piano', 'keyboard', 'music', 'instrument'] },
  { e: '🥁', k: ['drum', 'music', 'instrument'] },
  { e: '🎷', k: ['saxophone', 'sax', 'music', 'instrument'] },
  { e: '🎺', k: ['trumpet', 'music', 'brass', 'instrument'] },
  { e: '🎸', k: ['guitar', 'music', 'instrument', 'rock'] },
  { e: '🪕', k: ['banjo', 'music', 'string', 'instrument'] },
  { e: '🎻', k: ['violin', 'music', 'string', 'instrument'] },
  { e: '🎲', k: ['dice', 'game', 'random', 'roll'] },
  { e: '♟️', k: ['chess', 'pawn', 'game'] },
  { e: '🎯', k: ['dart', 'target', 'bullseye', 'game'] },
  { e: '🎳', k: ['bowling', 'game', 'sport'] },
  { e: '🎮', k: ['video game', 'controller', 'gaming'] },
  { e: '🎰', k: ['slot machine', 'casino', 'gamble', 'luck'] },
  { e: '🧩', k: ['puzzle', 'jigsaw', 'game'] },
  { e: '🃏', k: ['joker', 'card', 'playing'] },
  { e: '🀄', k: ['mahjong', 'game', 'tile'] },
  { e: '🎴', k: ['flower cards', 'game', 'cards'] },
  { e: '🎭', k: ['theater', 'arts'] },
  { e: '🖼️', k: ['frame', 'picture', 'art', 'photo'] },
  { e: '🎪', k: ['circus'] },
];

const TRAVEL: EmojiEntry[] = [
  { e: '🚗', k: ['car', 'automobile', 'vehicle', 'drive'] },
  { e: '🚕', k: ['taxi', 'cab', 'car'] },
  { e: '🚙', k: ['suv', 'car', 'vehicle'] },
  { e: '🚌', k: ['bus', 'vehicle', 'transport'] },
  { e: '🚎', k: ['trolleybus', 'transport'] },
  { e: '🏎️', k: ['racing car', 'formula', 'sport'] },
  { e: '🚓', k: ['police car', 'cop', 'vehicle'] },
  { e: '🚑', k: ['ambulance', 'medical', 'vehicle'] },
  { e: '🚒', k: ['fire truck', 'fire engine', 'vehicle'] },
  { e: '🚐', k: ['minibus', 'van', 'vehicle'] },
  { e: '🛻', k: ['pickup truck', 'vehicle'] },
  { e: '🚚', k: ['truck', 'delivery', 'vehicle'] },
  { e: '🚛', k: ['semi', 'truck', 'lorry', 'vehicle'] },
  { e: '🚜', k: ['tractor', 'farm', 'vehicle'] },
  { e: '🏍️', k: ['motorcycle', 'bike', 'vehicle'] },
  { e: '🛵', k: ['scooter', 'moped', 'vehicle'] },
  { e: '🚲', k: ['bicycle', 'bike', 'cycling'] },
  { e: '🛴', k: ['scooter', 'kick', 'vehicle'] },
  { e: '🚏', k: ['bus stop', 'sign', 'transport'] },
  { e: '🛣️', k: ['highway', 'road', 'motorway'] },
  { e: '🛤️', k: ['railway', 'track', 'train'] },
  { e: '⛽', k: ['fuel', 'gas', 'pump', 'station'] },
  { e: '🚨', k: ['police', 'light', 'emergency', 'siren'] },
  { e: '🚥', k: ['traffic light', 'horizontal', 'signal'] },
  { e: '🚦', k: ['traffic light', 'vertical', 'signal'] },
  { e: '🛑', k: ['stop sign', 'octagon', 'red'] },
  { e: '🚧', k: ['construction', 'barrier', 'warning'] },
  { e: '⚓', k: ['anchor', 'ship', 'sea', 'boat'] },
  { e: '⛵', k: ['sailboat', 'boat', 'sail', 'sea'] },
  { e: '🛶', k: ['canoe', 'boat', 'paddle'] },
  { e: '🚤', k: ['speedboat', 'boat', 'fast'] },
  { e: '🛳️', k: ['passenger ship', 'boat', 'cruise'] },
  { e: '⛴️', k: ['ferry', 'boat', 'transport'] },
  { e: '🛥️', k: ['motor boat', 'boat', 'yacht'] },
  { e: '🚢', k: ['ship', 'boat', 'cruise', 'cargo'] },
  { e: '✈️', k: ['airplane', 'plane', 'flight', 'fly'] },
  { e: '🛩️', k: ['small airplane', 'plane', 'flight'] },
  { e: '🛫', k: ['airplane', 'takeoff', 'departure', 'flight'] },
  { e: '🛬', k: ['airplane', 'landing', 'arrival', 'flight'] },
  { e: '🪂', k: ['parachute', 'parasail'] },
  { e: '💺', k: ['seat', 'chair', 'airplane'] },
  { e: '🚁', k: ['helicopter', 'chopper', 'flight'] },
  { e: '🚟', k: ['suspension railway', 'train', 'monorail'] },
  { e: '🚠', k: ['mountain cableway', 'cable', 'transport'] },
  { e: '🚡', k: ['aerial tramway', 'cable', 'gondola'] },
  { e: '🛰️', k: ['satellite', 'space', 'orbit'] },
  { e: '🚀', k: ['rocket', 'space', 'launch', 'fast'] },
  { e: '🛸', k: ['ufo', 'flying saucer', 'alien', 'space'] },
  { e: '🛎️', k: ['bellhop', 'bell', 'hotel', 'reception'] },
  { e: '🧳', k: ['luggage', 'suitcase', 'travel', 'bag'] },
  { e: '🗺️', k: ['map', 'world', 'travel', 'directions'] },
  { e: '🗼', k: ['tokyo tower', 'tower', 'japan'] },
  { e: '🗽', k: ['statue of liberty', 'statue', 'new york', 'freedom'] },
  { e: '🏯', k: ['japanese castle', 'castle', 'japan'] },
  { e: '🏰', k: ['castle', 'european', 'medieval', 'fortress'] },
  { e: '🏟️', k: ['stadium', 'sports', 'arena'] },
  { e: '🎡', k: ['ferris wheel', 'amusement', 'carnival'] },
  { e: '🎢', k: ['roller coaster', 'amusement', 'theme park'] },
  { e: '🎠', k: ['carousel', 'merry go round', 'amusement'] },
  { e: '⛲', k: ['fountain', 'water', 'park'] },
  { e: '⛱️', k: ['umbrella', 'beach', 'sun', 'ground'] },
  { e: '🏖️', k: ['beach', 'umbrella', 'sand', 'summer'] },
  { e: '🏝️', k: ['island', 'desert', 'palm', 'tropical'] },
  { e: '🏜️', k: ['desert', 'sand', 'dry'] },
  { e: '🌋', k: ['volcano', 'eruption', 'lava'] },
  { e: '⛰️', k: ['mountain', 'peak'] },
  { e: '🏔️', k: ['snowy mountain', 'mountain', 'snow'] },
  { e: '🗻', k: ['mount fuji', 'mountain', 'snow'] },
  { e: '🏕️', k: ['camping', 'tent', 'outdoors'] },
  { e: '🏠', k: ['house', 'home', 'building'] },
  { e: '🏡', k: ['house with garden', 'home', 'house'] },
  { e: '🏢', k: ['office building', 'work', 'skyscraper'] },
  { e: '🏤', k: ['post office', 'building', 'mail'] },
  { e: '🏥', k: ['hospital', 'medical', 'building'] },
  { e: '🏦', k: ['bank', 'building', 'money'] },
  { e: '🏨', k: ['hotel', 'building', 'accommodation'] },
  { e: '🏪', k: ['convenience store', 'shop', 'store'] },
  { e: '🏫', k: ['school', 'building', 'education'] },
  { e: '🏬', k: ['department store', 'shop', 'mall'] },
  { e: '🏭', k: ['factory', 'industrial', 'building'] },
  { e: '🏯', k: ['japanese castle'] },
  { e: '🏰', k: ['castle'] },
  { e: '💒', k: ['wedding', 'chapel', 'love', 'marriage'] },
  { e: '🗼', k: ['tokyo tower'] },
  { e: '🗽', k: ['statue of liberty'] },
  { e: '⛪', k: ['church', 'building', 'religion'] },
  { e: '🕌', k: ['mosque', 'building', 'religion', 'islam'] },
  { e: '🛕', k: ['hindu temple', 'temple', 'religion'] },
  { e: '🕍', k: ['synagogue', 'building', 'religion', 'jewish'] },
  { e: '⛩️', k: ['shinto shrine', 'torii', 'religion', 'japan'] },
  { e: '🕋', k: ['kaaba', 'mecca', 'islam', 'religion'] },
];

const OBJECTS: EmojiEntry[] = [
  { e: '⌚', k: ['watch', 'time', 'clock', 'wrist'] },
  { e: '📱', k: ['phone', 'mobile', 'cell', 'smartphone'] },
  { e: '📲', k: ['phone', 'mobile', 'arrow', 'transfer'] },
  { e: '💻', k: ['laptop', 'computer', 'notebook', 'mac'] },
  { e: '⌨️', k: ['keyboard', 'type', 'computer'] },
  { e: '🖥️', k: ['desktop', 'computer', 'monitor', 'screen'] },
  { e: '🖨️', k: ['printer', 'paper', 'office'] },
  { e: '🖱️', k: ['mouse', 'computer', 'click', 'pointer'] },
  { e: '🖲️', k: ['trackball', 'computer', 'pointer'] },
  { e: '🕹️', k: ['joystick', 'game', 'arcade'] },
  { e: '🗜️', k: ['clamp', 'tool', 'vise'] },
  { e: '💽', k: ['minidisc', 'disk', 'storage'] },
  { e: '💾', k: ['floppy', 'disk', 'save', 'storage'] },
  { e: '💿', k: ['cd', 'disc', 'optical'] },
  { e: '📀', k: ['dvd', 'disc', 'optical'] },
  { e: '📼', k: ['vhs', 'videocassette', 'tape'] },
  { e: '📷', k: ['camera', 'photo', 'picture'] },
  { e: '📸', k: ['camera', 'flash', 'photo'] },
  { e: '📹', k: ['video camera', 'camcorder', 'film'] },
  { e: '🎥', k: ['movie camera', 'film', 'video'] },
  { e: '📽️', k: ['film projector', 'movie', 'cinema'] },
  { e: '🎞️', k: ['film frames', 'movie', 'strip'] },
  { e: '📞', k: ['phone', 'telephone', 'call', 'receiver'] },
  { e: '☎️', k: ['telephone', 'phone', 'call'] },
  { e: '📟', k: ['pager', 'beeper', 'call'] },
  { e: '📠', k: ['fax', 'machine', 'office'] },
  { e: '📺', k: ['tv', 'television', 'screen'] },
  { e: '📻', k: ['radio', 'music', 'broadcast'] },
  { e: '🎙️', k: ['studio microphone', 'mic', 'podcast'] },
  { e: '🎚️', k: ['level slider', 'audio', 'mixer'] },
  { e: '🎛️', k: ['control knobs', 'audio', 'mixer'] },
  { e: '🧭', k: ['compass', 'navigation', 'direction'] },
  { e: '⏱️', k: ['stopwatch', 'time', 'timer'] },
  { e: '⏲️', k: ['timer clock', 'kitchen', 'timer'] },
  { e: '⏰', k: ['alarm clock', 'time', 'morning', 'wake'] },
  { e: '🕰️', k: ['mantelpiece clock', 'time', 'antique'] },
  { e: '⌛', k: ['hourglass', 'time', 'sand', 'done'] },
  { e: '⏳', k: ['hourglass', 'time', 'sand', 'flowing'] },
  { e: '📡', k: ['satellite antenna', 'dish', 'signal'] },
  { e: '🔋', k: ['battery', 'power', 'charge', 'energy'] },
  { e: '🔌', k: ['plug', 'electric', 'power', 'charge'] },
  { e: '💡', k: ['light bulb', 'idea', 'lamp', 'bright'] },
  { e: '🔦', k: ['flashlight', 'torch', 'light'] },
  { e: '🕯️', k: ['candle', 'light', 'wax', 'flame'] },
  { e: '🧯', k: ['fire extinguisher', 'safety', 'fire'] },
  { e: '🛢️', k: ['oil drum', 'barrel', 'petroleum'] },
  { e: '💸', k: ['money', 'dollar', 'cash', 'wings'] },
  { e: '💵', k: ['dollar', 'money', 'cash', 'bill'] },
  { e: '💴', k: ['yen', 'money', 'cash', 'japan'] },
  { e: '💶', k: ['euro', 'money', 'cash'] },
  { e: '💷', k: ['pound', 'money', 'cash', 'uk'] },
  { e: '🪙', k: ['coin', 'money', 'gold', 'silver'] },
  { e: '💰', k: ['money bag', 'cash', 'dollar', 'sack'] },
  { e: '💳', k: ['credit card', 'payment', 'plastic'] },
  { e: '💎', k: ['diamond', 'gem', 'jewel', 'precious'] },
  { e: '⚖️', k: ['balance scale', 'justice', 'weight'] },
  { e: '🪜', k: ['ladder', 'tool', 'climb'] },
  { e: '🧰', k: ['toolbox', 'tool', 'kit'] },
  { e: '🪛', k: ['screwdriver', 'tool'] },
  { e: '🔧', k: ['wrench', 'tool', 'fix'] },
  { e: '🔨', k: ['hammer', 'tool', 'nail'] },
  { e: '⚒️', k: ['hammer and pick', 'tool', 'mining'] },
  { e: '🛠️', k: ['hammer and wrench', 'tool', 'fix'] },
  { e: '⛏️', k: ['pick', 'tool', 'mining'] },
  { e: '🪚', k: ['carpentry saw', 'tool', 'wood'] },
  { e: '🔩', k: ['nut and bolt', 'tool', 'metal'] },
  { e: '⚙️', k: ['gear', 'settings', 'cog', 'mechanical'] },
  { e: '🪤', k: ['mouse trap', 'trap', 'cheese'] },
  { e: '🧱', k: ['brick', 'wall', 'building'] },
  { e: '⛓️', k: ['chain', 'link', 'locked'] },
  { e: '🧲', k: ['magnet', 'attract', 'magnetic'] },
  { e: '🔫', k: ['water pistol', 'gun', 'toy', 'shoot'] },
  { e: '💣', k: ['bomb', 'explosion', 'tnt'] },
  { e: '🧨', k: ['firecracker', 'explosive', 'new year'] },
  { e: '🪓', k: ['axe', 'hatchet', 'chop'] },
  { e: '🔪', k: ['knife', 'kitchen', 'cut', 'blade'] },
  { e: '🗡️', k: ['dagger', 'sword', 'blade'] },
  { e: '⚔️', k: ['crossed swords', 'fight', 'battle'] },
  { e: '🛡️', k: ['shield', 'protect', 'defense'] },
  { e: '🚬', k: ['cigarette', 'smoke', 'smoking'] },
  { e: '⚰️', k: ['coffin', 'death', 'casket'] },
  { e: '🪦', k: ['headstone', 'grave', 'tombstone'] },
  { e: '⚱️', k: ['urn', 'funeral', 'ashes'] },
  { e: '🏺', k: ['amphora', 'vase', 'ancient'] },
  { e: '🔮', k: ['crystal ball', 'fortune', 'magic', 'future'] },
  { e: '📿', k: ['prayer beads', 'rosary', 'religion'] },
  { e: '🧿', k: ['nazar amulet', 'evil eye', 'protection'] },
  { e: '💈', k: ['barber pole', 'salon', 'haircut'] },
  { e: '⚗️', k: ['alembic', 'chemistry', 'distill'] },
  { e: '🔭', k: ['telescope', 'space', 'stars', 'astronomy'] },
  { e: '🔬', k: ['microscope', 'science', 'lab'] },
  { e: '🕳️', k: ['hole', 'pit', 'gap'] },
  { e: '🩹', k: ['adhesive bandage', 'bandaid', 'first aid'] },
  { e: '🩺', k: ['stethoscope', 'doctor', 'medical'] },
  { e: '💊', k: ['pill', 'medicine', 'drug', 'capsule'] },
  { e: '💉', k: ['syringe', 'injection', 'vaccine', 'shot'] },
  { e: '🩸', k: ['blood', 'drop', 'red', 'donate'] },
  { e: '🧬', k: ['dna', 'biology', 'gene', 'science'] },
  { e: '🧫', k: ['petri dish', 'biology', 'lab', 'culture'] },
  { e: '🧪', k: ['test tube', 'chemistry', 'lab', 'experiment'] },
  { e: '🌡️', k: ['thermometer', 'temperature', 'weather'] },
  { e: '🧹', k: ['broom', 'sweep', 'clean', 'witch'] },
  { e: '🧺', k: ['basket', 'laundry', 'shopping'] },
  { e: '🧻', k: ['toilet paper', 'roll', 'bathroom'] },
  { e: '🚽', k: ['toilet', 'bathroom', 'wc'] },
  { e: '🚰', k: ['water closet', 'tap', 'faucet'] },
  { e: '🚿', k: ['shower', 'bath', 'water'] },
  { e: '🛁', k: ['bathtub', 'bath', 'relax'] },
  { e: '🛀', k: ['bath', 'person', 'relax'] },
  { e: '🧼', k: ['soap', 'clean', 'wash'] },
  { e: '🧽', k: ['sponge', 'clean', 'absorb'] },
  { e: '🧴', k: ['lotion bottle', 'soap', 'shampoo'] },
  { e: '🛎️', k: ['bellhop bell', 'hotel', 'reception'] },
  { e: '🔑', k: ['key', 'lock', 'unlock', 'password'] },
  { e: '🗝️', k: ['old key', 'skeleton', 'vintage'] },
  { e: '🚪', k: ['door', 'entrance', 'open'] },
  { e: '🪑', k: ['chair', 'seat', 'furniture'] },
  { e: '🛋️', k: ['couch', 'sofa', 'lounging'] },
  { e: '🛏️', k: ['bed', 'sleep', 'mattress'] },
  { e: '🛌', k: ['sleeping', 'bed', 'rest'] },
  { e: '🧸', k: ['teddy bear', 'toy', 'plush'] },
  { e: '🪆', k: ['nesting doll', 'russian', 'toy'] },
  { e: '🖼️', k: ['picture frame', 'art', 'photo'] },
  { e: '🪞', k: ['mirror', 'reflection'] },
  { e: '🪟', k: ['window', 'glass', 'view'] },
  { e: '🛍️', k: ['shopping bags', 'purchase', 'bags'] },
  { e: '🛒', k: ['shopping cart', 'trolley', 'buy'] },
  { e: '🎁', k: ['gift', 'present', 'wrapped'] },
  { e: '🎈', k: ['balloon', 'party', 'celebration'] },
  { e: '🎏', k: ['carp streamer', 'flag', 'japan'] },
  { e: '🎀', k: ['ribbon', 'bow', 'decoration'] },
  { e: '🎊', k: ['confetti ball', 'celebration', 'party'] },
  { e: '🎉', k: ['party popper', 'celebration', 'tada'] },
  { e: '🎎', k: ['japanese dolls', 'doll', 'festival'] },
  { e: '🏮', k: ['red lantern', 'light', 'chinese'] },
  { e: '🎐', k: ['wind chime', 'bell', 'japanese'] },
  { e: '🧧', k: ['red envelope', 'gift', 'chinese', 'money'] },
  { e: '✉️', k: ['envelope', 'mail', 'letter'] },
  { e: '📩', k: ['envelope', 'arrow', 'incoming', 'mail'] },
  { e: '📨', k: ['incoming envelope', 'mail', 'receive'] },
  { e: '📧', k: ['email', 'envelope', 'mail'] },
  { e: '💌', k: ['love letter', 'heart', 'mail'] },
  { e: '📥', k: ['inbox', 'tray', 'mail'] },
  { e: '📤', k: ['outbox', 'tray', 'mail'] },
  { e: '📦', k: ['package', 'box', 'parcel'] },
  { e: '🏷️', k: ['label', 'tag', 'price'] },
  { e: '📪', k: ['mailbox', 'closed', 'mail'] },
  { e: '📫', k: ['mailbox', 'open', 'mail', 'flag'] },
  { e: '📬', k: ['mailbox', 'open', 'mail', 'no flag'] },
  { e: '📭', k: ['mailbox', 'empty', 'mail'] },
  { e: '📯', k: ['postal horn', 'mail', 'announce'] },
  { e: '📜', k: ['scroll', 'paper', 'document'] },
  { e: '📃', k: ['page', 'document', 'paper'] },
  { e: '📄', k: ['page facing up', 'document', 'paper'] },
  { e: '📑', k: ['bookmark tabs', 'document', 'mark'] },
  { e: '🧾', k: ['receipt', 'paper', 'transaction'] },
  { e: '📊', k: ['bar chart', 'graph', 'stats'] },
  { e: '📈', k: ['chart increasing', 'graph', 'up', 'growth'] },
  { e: '📉', k: ['chart decreasing', 'graph', 'down'] },
  { e: '🗒️', k: ['spiral notepad', 'notes', 'paper'] },
  { e: '🗓️', k: ['spiral calendar', 'date', 'schedule'] },
  { e: '📆', k: ['tear off calendar', 'date', 'schedule'] },
  { e: '📅', k: ['calendar', 'date', 'schedule'] },
  { e: '🗑️', k: ['wastebasket', 'trash', 'delete'] },
  { e: '📇', k: ['card index', 'rolodex', 'contacts'] },
  { e: '🗃️', k: ['card file box', 'archive', 'storage'] },
  { e: '🗳️', k: ['ballot box', 'vote', 'election'] },
  { e: '🗄️', k: ['file cabinet', 'storage', 'office'] },
  { e: '📋', k: ['clipboard', 'document', 'list'] },
  { e: '📁', k: ['file folder', 'directory', 'storage'] },
  { e: '📂', k: ['open file folder', 'directory', 'storage'] },
  { e: '🗂️', k: ['card index dividers', 'organize', 'tabs'] },
  { e: '🗞️', k: ['rolled newspaper', 'news', 'paper'] },
  { e: '📰', k: ['newspaper', 'news', 'press'] },
  { e: '📓', k: ['notebook', 'journal', 'paper'] },
  { e: '📔', k: ['notebook', 'cover', 'journal'] },
  { e: '📒', k: ['ledger', 'notebook', 'accounting'] },
  { e: '📕', k: ['closed book', 'book', 'red'] },
  { e: '📗', k: ['green book', 'book'] },
  { e: '📘', k: ['blue book', 'book'] },
  { e: '📙', k: ['orange book', 'book'] },
  { e: '📚', k: ['books', 'stack', 'reading'] },
  { e: '📖', k: ['open book', 'reading', 'book'] },
  { e: '🔖', k: ['bookmark', 'mark', 'save'] },
  { e: '🧷', k: ['safety pin', 'pin', 'secure'] },
  { e: '🔗', k: ['link', 'chain', 'url'] },
  { e: '📎', k: ['paperclip', 'attach', 'clip'] },
  { e: '🖇️', k: ['linked paperclips', 'clip', 'attach'] },
  { e: '📐', k: ['triangular ruler', 'ruler', 'measure'] },
  { e: '📏', k: ['straight ruler', 'measure', 'ruler'] },
  { e: '🧮', k: ['abacus', 'count', 'calculate'] },
  { e: '📌', k: ['pushpin', 'pin', 'mark'] },
  { e: '📍', k: ['round pushpin', 'pin', 'location'] },
  { e: '✂️', k: ['scissors', 'cut', 'tool'] },
  { e: '🖊️', k: ['pen', 'write', 'ink'] },
  { e: '🖋️', k: ['fountain pen', 'write', 'ink'] },
  { e: '✒️', k: ['nib', 'pen', 'write'] },
  { e: '🖌️', k: ['paintbrush', 'paint', 'art'] },
  { e: '🖍️', k: ['crayon', 'color', 'draw'] },
  { e: '📝', k: ['memo', 'note', 'pencil', 'write'] },
  { e: '✏️', k: ['pencil', 'write', 'draw'] },
  { e: '🔍', k: ['magnifying glass', 'search', 'find'] },
  { e: '🔎', k: ['magnifying glass', 'search', 'find', 'tilted'] },
  { e: '🔏', k: ['lock with pen', 'secure', 'sign'] },
  { e: '🔐', k: ['lock with key', 'secure', 'unlock'] },
  { e: '🔒', k: ['locked', 'lock', 'secure'] },
  { e: '🔓', k: ['unlocked', 'lock', 'open'] },
];

const SYMBOLS: EmojiEntry[] = [
  { e: '❤️', k: ['heart', 'love', 'red'] },
  { e: '🧡', k: ['heart', 'orange', 'love'] },
  { e: '💛', k: ['heart', 'yellow', 'love'] },
  { e: '💚', k: ['heart', 'green', 'love'] },
  { e: '💙', k: ['heart', 'blue', 'love'] },
  { e: '💜', k: ['heart', 'purple', 'love'] },
  { e: '🖤', k: ['heart', 'black', 'love'] },
  { e: '🤍', k: ['heart', 'white', 'love'] },
  { e: '🤎', k: ['heart', 'brown', 'love'] },
  { e: '💔', k: ['broken heart', 'sad', 'heartbreak'] },
  { e: '❣️', k: ['heart exclamation', 'love', 'excited'] },
  { e: '💕', k: ['two hearts', 'love', 'affection'] },
  { e: '💞', k: ['revolving hearts', 'love'] },
  { e: '💓', k: ['beating heart', 'love', 'pulse'] },
  { e: '💗', k: ['growing heart', 'love'] },
  { e: '💖', k: ['sparkling heart', 'love', 'shine'] },
  { e: '💘', k: ['heart with arrow', 'cupid', 'love'] },
  { e: '💝', k: ['heart with ribbon', 'gift', 'love'] },
  { e: '💟', k: ['heart decoration', 'love'] },
  { e: '☮️', k: ['peace', 'dove', 'symbol'] },
  { e: '✝️', k: ['cross', 'christian', 'religion'] },
  { e: '☪️', k: ['star and crescent', 'islam', 'religion'] },
  { e: '🕉️', k: ['om', 'hindu', 'religion'] },
  { e: '☸️', k: ['wheel of dharma', 'buddhist', 'religion'] },
  { e: '✡️', k: ['star of david', 'jewish', 'religion'] },
  { e: '🔯', k: ['dotted six pointed star', 'star'] },
  { e: '♈', k: ['aries', 'zodiac', 'astrology'] },
  { e: '♉', k: ['taurus', 'zodiac', 'astrology'] },
  { e: '♊', k: ['gemini', 'zodiac', 'astrology'] },
  { e: '♋', k: ['cancer', 'zodiac', 'astrology'] },
  { e: '♌', k: ['leo', 'zodiac', 'astrology'] },
  { e: '♍', k: ['virgo', 'zodiac', 'astrology'] },
  { e: '♎', k: ['libra', 'zodiac', 'astrology'] },
  { e: '♏', k: ['scorpio', 'zodiac', 'astrology'] },
  { e: '♐', k: ['sagittarius', 'zodiac', 'astrology'] },
  { e: '♑', k: ['capricorn', 'zodiac', 'astrology'] },
  { e: '♒', k: ['aquarius', 'zodiac', 'astrology'] },
  { e: '♓', k: ['pisces', 'zodiac', 'astrology'] },
  { e: '⛎', k: ['ophiuchus', 'zodiac', 'snake'] },
  { e: '🔀', k: ['shuffle', 'random', 'tracks'] },
  { e: '🔁', k: ['repeat', 'loop', 'once'] },
  { e: '🔂', k: ['repeat single', 'loop', 'one'] },
  { e: '▶️', k: ['play', 'forward', 'triangle'] },
  { e: '⏩', k: ['fast forward', 'skip', 'forward'] },
  { e: '⏭️', k: ['next track', 'skip', 'forward'] },
  { e: '⏯️', k: ['play pause', 'toggle'] },
  { e: '◀️', k: ['reverse', 'back', 'triangle'] },
  { e: '⏪', k: ['fast reverse', 'rewind'] },
  { e: '⏮️', k: ['previous track', 'back'] },
  { e: '🔼', k: ['up button', 'triangle', 'up'] },
  { e: '⏫', k: ['fast up', 'double', 'triangle'] },
  { e: '🔽', k: ['down button', 'triangle', 'down'] },
  { e: '⏬', k: ['fast down', 'double', 'triangle'] },
  { e: '⏸️', k: ['pause', 'bars', 'hold'] },
  { e: '⏹️', k: ['stop', 'square'] },
  { e: '⏺️', k: ['record', 'circle', 'dot'] },
  { e: '⏏️', k: ['eject', 'pop out'] },
  { e: '🎦', k: ['cinema', 'movie', 'film'] },
  { e: '🔆', k: ['dim', 'low brightness', 'sun'] },
  { e: '🔅', k: ['low brightness', 'dim'] },
  { e: '📶', k: ['signal', 'antenna', 'bars'] },
  { e: '📳', k: ['vibration', 'phone', 'mode'] },
  { e: '📴', k: ['mobile off', 'phone', 'off'] },
  { e: '♀️', k: ['female', 'woman', 'sign'] },
  { e: '♂️', k: ['male', 'man', 'sign'] },
  { e: '⚧️', k: ['transgender', 'trans', 'symbol'] },
  { e: '✖️', k: ['multiply', 'x', 'cross'] },
  { e: '➕', k: ['plus', 'add', 'math'] },
  { e: '➖', k: ['minus', 'subtract', 'math'] },
  { e: '➗', k: ['divide', 'math', 'division'] },
  { e: '🟰', k: ['equal', 'math', '=' ] },
  { e: '♾️', k: ['infinity', 'forever', 'endless'] },
  { e: '‼️', k: ['double exclamation', 'bang'] },
  { e: '⁉️', k: ['interrobang', 'question', 'exclamation'] },
  { e: '❓', k: ['question', 'red', '?'] },
  { e: '❔', k: ['white question', '?'] },
  { e: '❕', k: ['white exclamation', '!'] },
  { e: '❗', k: ['exclamation', 'red', '!'] },
  { e: '〰️', k: ['wavy dash', 'wave'] },
  { e: '💱', k: ['currency exchange', 'money', 'swap'] },
  { e: '💲', k: ['dollar', 'money', 'usd'] },
  { e: '⚕️', k: ['medical', 'health', 'staff'] },
  { e: '♻️', k: ['recycle', 'green', 'reuse'] },
  { e: '⚜️', k: ['fleur de lis', 'lily', 'symbol'] },
  { e: '🔱', k: ['trident', 'poseidon', 'three'] },
  { e: '📛', k: ['name badge', 'tag', 'id'] },
  { e: '🔰', k: ['japanese beginner', 'green', 'symbol'] },
  { e: '⭕', k: ['circle', 'red', 'o', 'large'] },
  { e: '✅', k: ['check', 'checkmark', 'green', 'done'] },
  { e: '☑️', k: ['check box', 'ballot', 'check'] },
  { e: '✔️', k: ['check mark', 'done', 'yes'] },
  { e: '❌', k: ['cross', 'red', 'x', 'no', 'cancel'] },
  { e: '❎', k: ['cross mark button', 'no', 'red'] },
  { e: '➰', k: ['curly loop', 'loop'] },
  { e: '➿', k: ['double curly loop', 'loop'] },
  { e: '〽️', k: ['part alternation', 'mark'] },
  { e: '✳️', k: ['eight spoked asterisk', 'star'] },
  { e: '✴️', k: ['eight pointed star', 'star'] },
  { e: '❇️', k: ['sparkle', 'shiny'] },
  { e: '©️', k: ['copyright', 'c'] },
  { e: '®️', k: ['registered', 'r'] },
  { e: '™️', k: ['trademark', 'tm'] },
  { e: '#️⃣', k: ['hash', 'keycap', 'number'] },
  { e: '*️⃣', k: ['asterisk', 'keycap', 'star'] },
  { e: '0️⃣', k: ['zero', 'keycap', '0'] },
  { e: '1️⃣', k: ['one', 'keycap', '1'] },
  { e: '2️⃣', k: ['two', 'keycap', '2'] },
  { e: '3️⃣', k: ['three', 'keycap', '3'] },
  { e: '4️⃣', k: ['four', 'keycap', '4'] },
  { e: '5️⃣', k: ['five', 'keycap', '5'] },
  { e: '6️⃣', k: ['six', 'keycap', '6'] },
  { e: '7️⃣', k: ['seven', 'keycap', '7'] },
  { e: '8️⃣', k: ['eight', 'keycap', '8'] },
  { e: '9️⃣', k: ['nine', 'keycap', '9'] },
  { e: '🔟', k: ['ten', 'keycap', '10'] },
  { e: '🔠', k: ['abc', 'letters', 'uppercase'] },
  { e: '🔡', k: ['abc', 'letters', 'lowercase'] },
  { e: '🔢', k: ['numbers', '1234', 'symbols'] },
  { e: '🔣', k: ['symbols', 'input'] },
  { e: '🔤', k: ['abc', 'letters', 'lowercase'] },
  { e: '🅰️', k: ['a', 'letter', 'red'] },
  { e: '🆎', k: ['ab', 'blood type'] },
  { e: '🅱️', k: ['b', 'letter', 'red'] },
  { e: '🆑', k: ['cl', 'clear', 'button'] },
  { e: '🆒', k: ['cool', 'button'] },
  { e: '🆓', k: ['free', 'button'] },
  { e: 'ℹ️', k: ['info', 'i', 'information'] },
  { e: '🆔', k: ['id', 'button'] },
  { e: 'Ⓜ️', k: ['m', 'letter', 'circled'] },
  { e: '🆕', k: ['new', 'button'] },
  { e: '🆖', k: ['ng', 'no good', 'button'] },
  { e: '🅾️', k: ['o', 'letter', 'red'] },
  { e: '🆗', k: ['ok', 'button'] },
  { e: '🅿️', k: ['p', 'parking', 'letter'] },
  { e: '🆘', k: ['sos', 'help', 'button'] },
  { e: '🆙', k: ['up', 'button'] },
  { e: '🆚', k: ['vs', 'versus', 'button'] },
  { e: '🈁', k: ['here', 'japanese', 'button'] },
  { e: '🈂️', k: ['service', 'japanese', 'button'] },
  { e: '🈷️', k: ['monthly amount', 'japanese'] },
  { e: '🈶', k: ['not free', 'japanese'] },
  { e: '🈯', k: ['reserved', 'japanese'] },
  { e: '🉐', k: ['bargain', 'japanese'] },
  { e: '🈹', k: ['discount', 'japanese'] },
  { e: '🈚', k: ['free', 'japanese'] },
  { e: '🈲', k: ['prohibited', 'japanese'] },
  { e: '🉑', k: ['acceptable', 'japanese'] },
  { e: '🈸', k: ['apply', 'japanese'] },
  { e: '🈴', k: ['passing grade', 'japanese'] },
  { e: '🈳', k: ['vacancy', 'japanese'] },
  { e: '㊗️', k: ['congratulation', 'japanese'] },
  { e: '㊙️', k: ['secret', 'japanese'] },
  { e: '🈺', k: ['open for business', 'japanese'] },
  { e: '🈵', k: ['no vacancy', 'japanese'] },
  { e: '🔴', k: ['red circle', 'red', 'dot'] },
  { e: '🟠', k: ['orange circle', 'orange'] },
  { e: '🟡', k: ['yellow circle', 'yellow'] },
  { e: '🟢', k: ['green circle', 'green'] },
  { e: '🔵', k: ['blue circle', 'blue'] },
  { e: '🟣', k: ['purple circle', 'purple'] },
  { e: '🟤', k: ['brown circle', 'brown'] },
  { e: '⚫', k: ['black circle', 'black'] },
  { e: '⚪', k: ['white circle', 'white'] },
  { e: '🟥', k: ['red square', 'red'] },
  { e: '🟧', k: ['orange square', 'orange'] },
  { e: '🟨', k: ['yellow square', 'yellow'] },
  { e: '🟩', k: ['green square', 'green'] },
  { e: '🟦', k: ['blue square', 'blue'] },
  { e: '🟪', k: ['purple square', 'purple'] },
  { e: '🟫', k: ['brown square', 'brown'] },
  { e: '⬛', k: ['black square', 'black'] },
  { e: '⬜', k: ['white square', 'white'] },
  { e: '◼️', k: ['black medium square'] },
  { e: '◻️', k: ['white medium square'] },
  { e: '◾', k: ['black small square'] },
  { e: '◽', k: ['white small square'] },
  { e: '▪️', k: ['black very small square'] },
  { e: '▫️', k: ['white very small square'] },
  { e: '🔶', k: ['orange diamond', 'large'] },
  { e: '🔷', k: ['blue diamond', 'large'] },
  { e: '🔸', k: ['orange diamond', 'small'] },
  { e: '🔹', k: ['blue diamond', 'small'] },
  { e: '🔺', k: ['red triangle', 'up'] },
  { e: '🔻', k: ['red triangle', 'down'] },
  { e: '💠', k: ['diamond with dot', 'blue'] },
  { e: '🔘', k: ['radio button', 'circle'] },
  { e: '🔳', k: ['white square button'] },
  { e: '🔲', k: ['black square button'] },
];

const FLAGS: EmojiEntry[] = [
  { e: '🏴', k: ['black flag', 'flag'] },
  { e: '🏳️', k: ['white flag', 'flag', 'surrender'] },
  { e: '🏁', k: ['checkered flag', 'finish', 'racing'] },
  { e: '🚩', k: ['triangular flag', 'red', 'pin'] },
  { e: '🏳️‍🌈', k: ['rainbow flag', 'pride', 'lgbtq'] },
  { e: '🏳️‍⚧️', k: ['transgender flag', 'trans', 'pride'] },
  { e: '🏴‍☠️', k: ['pirate flag', 'skull', 'jolly roger'] },
  { e: '🇪🇹', k: ['ethiopia', 'ethiopian', 'flag'] },
  { e: '🇪🇷', k: ['eritrea', 'eritrean', 'flag'] },
  { e: '🇩🇯', k: ['djibouti', 'flag'] },
  { e: '🇸🇴', k: ['somalia', 'somali', 'flag'] },
  { e: '🇸🇩', k: ['sudan', 'sudanese', 'flag'] },
  { e: '🇸🇸', k: ['south sudan', 'flag'] },
  { e: '🇰🇪', k: ['kenya', 'kenyan', 'flag'] },
  { e: '🇺🇬', k: ['uganda', 'ugandan', 'flag'] },
  { e: '🇹🇿', k: ['tanzania', 'flag'] },
  { e: '🇷🇼', k: ['rwanda', 'rwandan', 'flag'] },
  { e: '🇧🇮', k: ['burundi', 'flag'] },
  { e: '🇪🇬', k: ['egypt', 'egyptian', 'flag'] },
  { e: '🇱🇾', k: ['libya', 'flag'] },
  { e: '🇹🇳', k: ['tunisia', 'flag'] },
  { e: '🇩🇿', k: ['algeria', 'flag'] },
  { e: '🇲🇦', k: ['morocco', 'moroccan', 'flag'] },
  { e: '🇳🇬', k: ['nigeria', 'nigerian', 'flag'] },
  { e: '🇬🇭', k: ['ghana', 'ghanaian', 'flag'] },
  { e: '🇿🇦', k: ['south africa', 'flag'] },
  { e: '🇺🇸', k: ['united states', 'usa', 'america', 'flag'] },
  { e: '🇨🇦', k: ['canada', 'canadian', 'flag'] },
  { e: '🇬🇧', k: ['united kingdom', 'uk', 'britain', 'flag'] },
  { e: '🇫🇷', k: ['france', 'french', 'flag'] },
  { e: '🇩🇪', k: ['germany', 'german', 'flag'] },
  { e: '🇮🇹', k: ['italy', 'italian', 'flag'] },
  { e: '🇪🇸', k: ['spain', 'spanish', 'flag'] },
  { e: '🇵🇹', k: ['portugal', 'portuguese', 'flag'] },
  { e: '🇳🇱', k: ['netherlands', 'dutch', 'flag'] },
  { e: '🇧🇪', k: ['belgium', 'flag'] },
  { e: '🇨🇭', k: ['switzerland', 'swiss', 'flag'] },
  { e: '🇦🇹', k: ['austria', 'flag'] },
  { e: '🇸🇪', k: ['sweden', 'flag'] },
  { e: '🇳🇴', k: ['norway', 'flag'] },
  { e: '🇩🇰', k: ['denmark', 'flag'] },
  { e: '🇫🇮', k: ['finland', 'flag'] },
  { e: '🇮🇪', k: ['ireland', 'flag'] },
  { e: '🇵🇱', k: ['poland', 'flag'] },
  { e: '🇷🇺', k: ['russia', 'russian', 'flag'] },
  { e: '🇺🇦', k: ['ukraine', 'flag'] },
  { e: '🇹🇷', k: ['turkey', 'turkish', 'flag'] },
  { e: '🇬🇷', k: ['greece', 'flag'] },
  { e: '🇨🇳', k: ['china', 'chinese', 'flag'] },
  { e: '🇯🇵', k: ['japan', 'japanese', 'flag'] },
  { e: '🇰🇷', k: ['south korea', 'korea', 'flag'] },
  { e: '🇮🇳', k: ['india', 'indian', 'flag'] },
  { e: '🇵🇰', k: ['pakistan', 'flag'] },
  { e: '🇧🇩', k: ['bangladesh', 'flag'] },
  { e: '🇮🇩', k: ['indonesia', 'flag'] },
  { e: '🇲🇾', k: ['malaysia', 'flag'] },
  { e: '🇸🇬', k: ['singapore', 'flag'] },
  { e: '🇵🇭', k: ['philippines', 'flag'] },
  { e: '🇹🇭', k: ['thailand', 'flag'] },
  { e: '🇻🇳', k: ['vietnam', 'flag'] },
  { e: '🇦🇺', k: ['australia', 'aussie', 'flag'] },
  { e: '🇳🇿', k: ['new zealand', 'flag'] },
  { e: '🇧🇷', k: ['brazil', 'brazilian', 'flag'] },
  { e: '🇦🇷', k: ['argentina', 'flag'] },
  { e: '🇲🇽', k: ['mexico', 'mexican', 'flag'] },
  { e: '🇨🇴', k: ['colombia', 'flag'] },
  { e: '🇵🇪', k: ['peru', 'flag'] },
  { e: '🇨🇱', k: ['chile', 'flag'] },
  { e: '🇸🇦', k: ['saudi arabia', 'saudi', 'flag'] },
  { e: '🇦🇪', k: ['united arab emirates', 'uae', 'dubai', 'flag'] },
  { e: '🇶🇦', k: ['qatar', 'flag'] },
  { e: '🇰🇼', k: ['kuwait', 'flag'] },
  { e: '🇧🇭', k: ['bahrain', 'flag'] },
  { e: '🇴🇲', k: ['oman', 'flag'] },
  { e: '🇾🇪', k: ['yemen', 'flag'] },
  { e: '🇮🇶', k: ['iraq', 'flag'] },
  { e: '🇮🇷', k: ['iran', 'flag'] },
  { e: '🇮🇱', k: ['israel', 'flag'] },
  { e: '🇯🇴', k: ['jordan', 'flag'] },
  { e: '🇱🇧', k: ['lebanon', 'flag'] },
  { e: '🇸🇾', k: ['syria', 'flag'] },
  { e: '🇦🇪', k: ['emirates'] },
];

// ─── Build category metadata ────────────────────────────────
type Category = { id: string; label: string; icon: string; emojis: EmojiEntry[] };

const CATEGORIES: Category[] = [
  { id: 'food', label: 'Food', icon: '🍽️', emojis: dedupe(FOOD) },
  { id: 'drinks', label: 'Drinks', icon: '🥤', emojis: dedupe(DRINKS) },
  { id: 'people', label: 'People', icon: '👤', emojis: dedupe(PEOPLE) },
  { id: 'animals', label: 'Animals', icon: '🐶', emojis: dedupe(ANIMALS) },
  { id: 'nature', label: 'Nature', icon: '🌿', emojis: dedupe(NATURE) },
  { id: 'activities', label: 'Activities', icon: '⚽', emojis: dedupe(ACTIVITIES) },
  { id: 'travel', label: 'Travel', icon: '✈️', emojis: dedupe(TRAVEL) },
  { id: 'objects', label: 'Objects', icon: '💡', emojis: dedupe(OBJECTS) },
  { id: 'symbols', label: 'Symbols', icon: '❤️', emojis: dedupe(SYMBOLS) },
  { id: 'flags', label: 'Flags', icon: '🏁', emojis: dedupe(FLAGS) },
];

function dedupe(list: EmojiEntry[]): EmojiEntry[] {
  const seen = new Set<string>();
  const out: EmojiEntry[] = [];
  for (const entry of list) {
    if (seen.has(entry.e)) continue;
    seen.add(entry.e);
    out.push(entry);
  }
  return out;
}

// All emojis flattened for search
const ALL_EMOJIS: EmojiEntry[] = dedupe([
  ...FOOD, ...DRINKS, ...PEOPLE, ...ANIMALS, ...NATURE,
  ...ACTIVITIES, ...TRAVEL, ...OBJECTS, ...SYMBOLS, ...FLAGS,
]);

const RECENT_KEY = 'yeneqr:emoji-picker:recent';
const MAX_RECENT = 24;

function loadRecent(): string[] {
  if (typeof window === 'undefined') return [];
  try {
    const raw = localStorage.getItem(RECENT_KEY);
    if (!raw) return [];
    const arr = JSON.parse(raw);
    return Array.isArray(arr) ? arr.filter((x) => typeof x === 'string').slice(0, MAX_RECENT) : [];
  } catch {
    return [];
  }
}

function saveRecent(emojis: string[]) {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(RECENT_KEY, JSON.stringify(emojis.slice(0, MAX_RECENT)));
  } catch {
    // ignore
  }
}

// ─── Component ──────────────────────────────────────────────

export interface EmojiPickerProps {
  value: string;
  onChange: (emoji: string) => void;
  /** Optional className for the root container */
  className?: string;
}

export function EmojiPicker({ value, onChange, className }: EmojiPickerProps) {
  const [activeCategory, setActiveCategory] = useState<string>('food');
  const [search, setSearch] = useState('');
  const [recent, setRecent] = useState<string[]>([]);
  const gridRef = useRef<HTMLDivElement>(null);

  // Load recently-used emojis on mount
  useEffect(() => {
    setRecent(loadRecent());
  }, []);

  const handleSelect = (emoji: string) => {
    onChange(emoji);
    // Update recently-used list (move to front, dedupe, cap at MAX_RECENT)
    setRecent((prev) => {
      const next = [emoji, ...prev.filter((e) => e !== emoji)].slice(0, MAX_RECENT);
      saveRecent(next);
      return next;
    });
  };

  // Filtered emojis for the active category (or search results)
  const displayed: EmojiEntry[] = useMemo(() => {
    if (search.trim()) {
      const q = search.toLowerCase().trim();
      return ALL_EMOJIS.filter((entry) =>
        entry.k.some((kw) => kw.includes(q)) || entry.e.includes(q)
      );
    }
    const cat = CATEGORIES.find((c) => c.id === activeCategory);
    return cat ? cat.emojis : [];
  }, [search, activeCategory]);

  // Reset scroll to top when category or search changes
  useEffect(() => {
    if (gridRef.current) gridRef.current.scrollTop = 0;
  }, [activeCategory, search]);

  const showRecent = !search.trim() && recent.length > 0 && activeCategory === 'food';

  return (
    <div className={cn('rounded-lg border bg-background', className)}>
      {/* Search bar */}
      <div className="p-2 border-b">
        <div className="relative">
          <Search className="absolute left-2 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
          <Input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search emojis (e.g. pizza, coffee, heart...)"
            className="h-8 pl-8 pr-8 text-xs"
          />
          {search && (
            <button
              type="button"
              onClick={() => setSearch('')}
              className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
              aria-label="Clear search"
            >
              <X className="h-3.5 w-3.5" />
            </button>
          )}
        </div>
      </div>

      {/* Recently used (only on default category + no search) */}
      {showRecent && (
        <div className="px-2 py-1.5 border-b">
          <p className="text-[10px] font-medium text-muted-foreground mb-1 uppercase tracking-wide">Recently used</p>
          <div className="grid grid-cols-12 gap-0.5">
            {recent.map((emoji, idx) => (
              <button
                key={`recent-${idx}-${emoji}`}
                type="button"
                onClick={() => handleSelect(emoji)}
                className={`h-7 w-7 rounded flex items-center justify-center text-base transition-all hover:bg-accent ${
                  value === emoji ? 'bg-primary/20 ring-1 ring-primary' : ''
                }`}
                title={emoji}
              >
                {emoji}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Category tabs (hidden during search) */}
      {!search.trim() && (
        <div className="flex gap-0.5 px-2 py-1.5 border-b overflow-x-auto scrollbar-hide" style={{ scrollbarWidth: 'none' }}>
          {CATEGORIES.map((cat) => (
            <button
              key={cat.id}
              type="button"
              onClick={() => setActiveCategory(cat.id)}
              className={`h-7 min-w-7 px-1.5 rounded flex items-center justify-center text-base transition-all shrink-0 ${
                activeCategory === cat.id
                  ? 'bg-primary/15 ring-1 ring-primary'
                  : 'hover:bg-accent'
              }`}
              title={cat.label}
              aria-label={cat.label}
            >
              {cat.icon}
            </button>
          ))}
        </div>
      )}

      {/* Emoji grid */}
      <div
        ref={gridRef}
        className="p-2 max-h-56 overflow-y-auto"
      >
        {displayed.length === 0 ? (
          <div className="py-8 text-center text-xs text-muted-foreground">
            {search.trim() ? `No emojis match "${search}"` : 'No emojis in this category'}
          </div>
        ) : (
          <div className="grid grid-cols-10 gap-0.5">
            {displayed.map((entry, idx) => (
              <button
                key={`${entry.e}-${idx}`}
                type="button"
                onClick={() => handleSelect(entry.e)}
                className={`h-7 w-7 rounded flex items-center justify-center text-base transition-all hover:bg-accent hover:scale-110 ${
                  value === entry.e ? 'bg-primary/20 ring-1 ring-primary' : ''
                }`}
                title={entry.k[0]}
              >
                {entry.e}
              </button>
            ))}
          </div>
        )}
      </div>

      {/* Footer: currently selected + clear */}
      <div className="px-2 py-1.5 border-t flex items-center justify-between">
        <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
          <span>Selected:</span>
          <span className="text-base">{value || '—'}</span>
        </div>
        {value && (
          <button
            type="button"
            onClick={() => onChange('')}
            className="text-[11px] text-muted-foreground hover:text-destructive underline"
          >
            Clear
          </button>
        )}
      </div>
    </div>
  );
}

export default EmojiPicker;
